### ISSUE TITLE
Docker compose部署时 会自建存储卷 有必要映射吗？

### ISSUE THREAD

**Issue by gzxiexl** [jamebal/jmal-cloud-view#103]
jmalcloud_server ：
![image](https://github.com/jamebal/jmal-cloud-view/assets/40417977/ef27c480-1af6-4ddb-be0f-934896b0e46f)
jmalcloud_mongodb ：
![image](https://github.com/jamebal/jmal-cloud-view/assets/40417977/149e416f-06a5-47c2-810b-2501b561cc20)
jmalcloud_office：
![image](https://github.com/jamebal/jmal-cloud-view/assets/40417977/28a6d3f5-c737-41d3-ba33-b7b591984ca7)
每次重建容器会搞出一堆卷，
其中/usr/share/fonts/truetype/custom 看起来是onlyoffice添加字体用的 建议指定一下是不是更好？

**Comment by gzxiexl** [comment]
![image](https://github.com/jamebal/jmal-cloud-view/assets/40417977/faa76665-094d-430b-a445-26f74b73d354)
我在onlyoffice wiki上查询的 看起来也是建议大佬改进下docker compose.yaml

**Comment by jamebal** [comment]
这个有需求可以自己改`docker-compose.yml`, 数据都是在jmalcloud中的, office容器的数据可以随时删除
