### ISSUE TITLE
建议不要取消文件夹右键“复制下载链接”

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#114]
这个功能非常实用，强烈建议不要取消。

例如以下使用场景：
A文件夹是做了分享的文件夹，A文件夹内有许多子文件夹，假如我只需要分享A文件夹下的某个文件夹，这时我只需要右键复制该文件的下载链接即可分享给他人，他人点击链接后直接下载成压缩包格式，在没有取消文件夹右键“复制下载链接”时，这很方便点击链接下载的人。如果取消了且正好该文件夹下有多个子文件或文件夹那我一个一个去复制就失去了效率并且繁琐，如果我直接下载下来分享给别人又失去了网盘的便利性，如果我直接分享A文件夹的链接他人还需要从众多的子文件夹内去寻找，确实影响效率，所有我建议不要取消这个功能，这个功能非常的实用，并且好用。

![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/4083cc47-fa20-4871-aeeb-dcb46f2402c1)

**Comment by jamebal** [comment]
ok, 下个版本加上

**Comment by jamebal** [comment]
目前只是去掉了用户界面的上文件夹的"复制下载链接", 分享界面仍然可以在文件夹上复制下载连接

**Comment by Xiaoph123** [comment]
> 目前只是去掉了用户界面的上文件夹的"复制下载链接", 分享界面仍然可以在文件夹上复制下载连接, 点击全选也可下载整个分享目录

我去看一下，我的没有显示“复制下载链接”，我去测测

**Comment by Xiaoph123** [comment]
> 目前只是去掉了用户界面的上文件夹的"复制下载链接", 分享界面仍然可以在文件夹上复制下载连接, 点击全选也可下载整个分享目录

分享界面的文件夹“复制下载链接”的确没有了，只能分享文件，不能分享文件夹，我重新分享也不行
<img width="776" alt="PixPin_2024-05-23_10-32-02" src="https://github.com/jamebal/jmal-cloud-view/assets/106538519/17edd234-12c3-4136-ade5-b4967d89430e">
<img width="636" alt="PixPin_2024-05-23_10-32-36" src="https://github.com/jamebal/jmal-cloud-view/assets/106538519/23bb37b8-1a73-49d9-bd92-cc848671975e">

**Comment by jamebal** [comment]
<img width="1076" alt="截屏2024-05-23 10 47 14" src="https://github.com/jamebal/jmal-cloud-view/assets/49510841/aac2e68b-97da-4ded-8352-a43a13c99de8">
这个分享界面

**Comment by Xiaoph123** [comment]
> > 目前只是去掉了用户界面的上文件夹的"复制下载链接", 分享界面仍然可以在文件夹上复制下载连接, 点击全选也可下载整个分享目录
> 
> 分享界面的文件夹“复制下载链接”的确没有了，只能分享文件，不能分享文件夹，我重新分享也不行
> <img width="776" alt="PixPin_2024-05-23_10-32-02" src="https://github.com/jamebal/jmal-cloud-view/assets/106538519/17edd234-12c3-4136-ade5-b4967d89430e">
> <img width="636" alt="PixPin_2024-05-23_10-32-36" src="https://github.com/jamebal/jmal-cloud-view/assets/106538519/23bb37b8-1a73-49d9-bd92-cc848671975e">
> 

我觉得还是在这个界面比较好点，因为那样会比较方便，我经常会在分享的文件夹内更新数据，上传新文件或文件夹，现在是每次我上传后都要去到“分享模块”的分享界面，然后再去右键“复制下载链接”，这样有点不方便

**Comment by jamebal** [comment]
> > > 目前只是去掉了用户界面的上文件夹的"复制下载链接", 分享界面仍然可以在文件夹上复制下载连接, 点击全选也可下载整个分享目录
> > 
> > 
> > 分享界面的文件夹“复制下载链接”的确没有了，只能分享文件，不能分享文件夹，我重新分享也不行
> > <img alt="PixPin_2024-05-23_10-32-02" width="776" src="https://private-user-images.githubusercontent.com/106538519/333014640-17edd234-12c3-4136-ade5-b4967d89430e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzM3NzcsIm5iZiI6MTcxNjQzMzQ3NywicGF0aCI6Ii8xMDY1Mzg1MTkvMzMzMDE0NjQwLTE3ZWRkMjM0LTEyYzMtNDEzNi1hZGU1LWI0OTY3ZDg5NDMwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMzA0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWI3MTMwNjY4MWEzZTY2NmZhZDBmMDgxY2Y4MWI0ODBmYTE3N2U0ZmRlMmI2ZTY3NTk2MzA2ZTZhM2E0MzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mdsoKgDG-dZCLHQ7bCZND08mdQCfiLv3WcIMhvGRP04">
> > <img alt="PixPin_2024-05-23_10-32-36" width="636" src="https://private-user-images.githubusercontent.com/106538519/333014652-23bb37b8-1a73-49d9-bd92-cc848671975e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzM3NzcsIm5iZiI6MTcxNjQzMzQ3NywicGF0aCI6Ii8xMDY1Mzg1MTkvMzMzMDE0NjUyLTIzYmIzN2I4LTFhNzMtNDlkOS1iZDkyLWNjODQ4NjcxOTc1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMzA0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmZmZWZhM2UzNTY2ZGI0N2Q1ZmU2ZWI2YjZhYjdmZjkxNGFkYmZmYzVmN2U4ZGYyMGVlZDhkNzZlOTU4Y2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kYhib2TvHgLkApXaNTbZNRUAOJ4_f7-nr-WECmnxsUA">
> 
> 我觉得还是在这个界面比较好点，因为那样会比较方便，我经常会在分享的文件夹内更新数据，上传新文件或文件夹，现在是每次我上传后都要去到“分享模块”的分享界面，然后再去右键“复制下载链接”，这样有点不方便

下个版本加上

**Comment by Xiaoph123** [comment]
> > > > 目前只是去掉了用户界面的上文件夹的"复制下载链接", 分享界面仍然可以在文件夹上复制下载连接, 点击全选也可下载整个分享目录
> > > 
> > > 
> > > 分享界面的文件夹“复制下载链接”的确没有了，只能分享文件，不能分享文件夹，我重新分享也不行
> > > <img alt="PixPin_2024-05-23_10-32-02" width="776" src="https://private-user-images.githubusercontent.com/106538519/333014640-17edd234-12c3-4136-ade5-b4967d89430e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzM3NzcsIm5iZiI6MTcxNjQzMzQ3NywicGF0aCI6Ii8xMDY1Mzg1MTkvMzMzMDE0NjQwLTE3ZWRkMjM0LTEyYzMtNDEzNi1hZGU1LWI0OTY3ZDg5NDMwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMzA0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWI3MTMwNjY4MWEzZTY2NmZhZDBmMDgxY2Y4MWI0ODBmYTE3N2U0ZmRlMmI2ZTY3NTk2MzA2ZTZhM2E0MzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mdsoKgDG-dZCLHQ7bCZND08mdQCfiLv3WcIMhvGRP04">
> > > <img alt="PixPin_2024-05-23_10-32-36" width="636" src="https://private-user-images.githubusercontent.com/106538519/333014652-23bb37b8-1a73-49d9-bd92-cc848671975e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzM3NzcsIm5iZiI6MTcxNjQzMzQ3NywicGF0aCI6Ii8xMDY1Mzg1MTkvMzMzMDE0NjUyLTIzYmIzN2I4LTFhNzMtNDlkOS1iZDkyLWNjODQ4NjcxOTc1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMzA0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmZmZWZhM2UzNTY2ZGI0N2Q1ZmU2ZWI2YjZhYjdmZjkxNGFkYmZmYzVmN2U4ZGYyMGVlZDhkNzZlOTU4Y2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kYhib2TvHgLkApXaNTbZNRUAOJ4_f7-nr-WECmnxsUA">
> > 
> > 我觉得还是在这个界面比较好点，因为那样会比较方便，我经常会在分享的文件夹内更新数据，上传新文件或文件夹，现在是每次我上传后都要去到“分享模块”的分享界面，然后再去右键“复制下载链接”，这样有点不方便
> 
> 下个版本加上

好的，谢谢大佬
