### ISSUE TITLE
网盘API登不进去

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#115]
我登录网盘API的地址显示报错：

![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/ced9cb92-ef2c-4076-8d44-beaa7e96d2d9)

![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/6b8ec5d7-7466-4d3f-b732-af450bed1992)

**Comment by jamebal** [comment]
外网访问api地址, 需要单独代理

**Comment by Xiaoph123** [comment]
> 外网访问api地址, 需要单独代理

我给nginx增加了个server块，我不知道我的配置是否有问题，您帮我看下
![mmexport1716434060296.png](https://github.com/jamebal/jmal-cloud-view/assets/106538519/15597341-23cf-4ef4-a2cf-6b9dbfcde7bb)

**Comment by jamebal** [comment]
`proxy_pass http://localhost:7072/public/api;`
这个改成: `proxy_pass http://localhost:7072;`
访问api: https://xxx:9001/public/api

**Comment by Xiaoph123** [comment]
> `proxy_pass http://localhost:7072/public/api;`
> 这个改成: `proxy_pass http://localhost:7072;`
> 访问api: https://xxx:9001/public/api

我试一下

**Comment by Xiaoph123** [comment]
> `proxy_pass http://localhost:7072/public/api;`
> 这个改成: `proxy_pass http://localhost:7072;`
> 访问api: https://xxx:9001/public/api

已成功登录，非常感谢🙏
![mmexport1716434642859.png](https://github.com/jamebal/jmal-cloud-view/assets/106538519/039e2512-7f20-4f76-ac39-0cf689d7a8e9)
