### ISSUE TITLE
请问能否应用在ARM64或者ARM32的设备上呢？

### ISSUE THREAD

**Issue by chenryace** [jamebal/jmal-cloud-view#12]
比如玩客云或者N1的armbian或者openwrt上（可跑docker），如果不行，请问以后有进一步适配这些低端设备的计划吗？
目前尝试在X86的群晖上跑，感觉运用起来比coludreve好太多了，而且直接映射文件夹出来就好了。不过主力当然用群晖啦。
这个项目的权限管理真的好，测试网址中打算用admin来修改上传权限，都提示不可行。作为使用者非常看好，要真能用在这些低端低功耗设备上，绝对可以取代filebrowser（包括灯大修改的），所以作者加油！！
BTW，如果可以通过RCLONE，打通onedrive，就更犀利了。

**Comment by jamebal** [comment]
目前不适合在低端设备上运行哦，以后可能会出一个轻量级的版本
