### ISSUE TITLE
创建账户时报错“string length only support string input”不知道应该怎么解决

### ISSUE THREAD

**Issue by Wagoodnight** [jamebal/jmal-cloud-view#133]
如图，提issues时刚clone的，使用./jc.sh install安装的
![image](https://github.com/jamebal/jmal-cloud-view/assets/89726674/7fc76236-1e2d-4741-acb1-6693735a3f70)
重置账户也没用，就是不让我创建账户。
不知道怎么解决，恳请佬帮忙。

**Comment by jamebal** [comment]
是第一次安装还是升级的,如果是第一次安装推荐设置这种方式: https://github.com/jamebal/jmal-cloud-view?tab=readme-ov-file#%E9%83%A8%E7%BD%B2

**Comment by Wagoodnight** [comment]
> 是第一次安装还是升级的,如果是第一次安装推荐设置这种方式: https://github.com/jamebal/jmal-cloud-view?tab=readme-ov-file#%E9%83%A8%E7%BD%B2

十分感谢你能在百忙之中回复我的issue
我是全新安装的，我刚刚使用了你推荐的安装方式
![image](https://github.com/jamebal/jmal-cloud-view/assets/89726674/a61a3717-c027-4f57-824d-84d2a119a6a6)
![image](https://github.com/jamebal/jmal-cloud-view/assets/89726674/3f9e55b2-3cc8-49a3-91e9-9b0473a8922e)

**Comment by Wagoodnight** [comment]
刚刚我换了一个机器重新构建，发现卡在这个界面动不了了。
![image](https://github.com/jamebal/jmal-cloud-view/assets/89726674/aac489d4-5b61-4c6f-a4bf-139e85eac470)
用户改为jmalcloud也一样。同样也重置了密码。
![image](https://github.com/jamebal/jmal-cloud-view/assets/89726674/efe28ea7-e898-4125-8161-4729029a165c)
yml使用的是你给出的，只修改了文件映射路径

**Comment by jamebal** [comment]
解决办法: 
1. 停止并删除容器 
```shell
docker-cmpose down
```
2. 删除目录`./docker/jmalcloud/mongodb/data/db`
3. 更新镜像: 
 ```shell
docker-cmpose pull && docker-compose up -d
```

**Comment by TM0088** [comment]
降級到2.8.4解決了問題

**Comment by TM0088** [comment]
> 降級到2.8.4解決了問題

fastjson2組件問題?

**Comment by jamebal** [comment]
加载默认角色失败的问题, 最新镜像已修复该问题

**Comment by Wagoodnight** [comment]
十分感谢您，问题已经解决了。
