### ISSUE TITLE
建议：整合kkfileview实现强大的全格式预览

### ISSUE THREAD

**Issue by death4444** [jamebal/jmal-cloud-view#136]
咱既然都是网盘了，全文搜索也支持了，搜到的文件给个预览不过分吧？
强烈推荐整合kkfileview，实现全格式预览
kkfileview项目地址：[kkFileView](https://github.com/kekingcn/kkFileView)

**Comment by jamebal** [comment]
不支持预览的格式可以补充, 没必要整合进去

**Comment by death4444** [comment]
提出问题之后我就后悔了，正准备来关闭，结果大佬光速回复，厉害啦！
确实没必要，本来就有onlyoffice了，不光预览还可以编辑。加载比单纯预览的慢一点，但个人用的网盘，等等也还好。
