### ISSUE TITLE
镜像拉取不到

### ISSUE THREAD

**Issue by shengruicai** [jamebal/jmal-cloud-view#147]
麻烦问一下，Centos7环境下 执行./jc.sh install 或手动执行拉取都提示提示：
Error response from daemon: missing signature key

Docker 和 Docker Compose也都安装了需要怎么解决？

**Comment by jamebal** [comment]
其他镜像能正常拉取吗

**Comment by jamebal** [comment]
to https://github.com/jamebal/jmal-cloud-view/issues/177#issuecomment-2159725355
