### ISSUE TITLE
网盘仓库支持的最大容量可以调整吗？目前似乎只允许15GB。

### ISSUE THREAD

**Issue by mawanglin** [jamebal/jmal-cloud-view#16]
![image](https://user-images.githubusercontent.com/3214028/135372883-e4746a3b-3531-4eb5-9752-d2edeab3fe02.png)
如上图，已经存入文件的容量超过了允许的最大上限15GB，上传文件时会提示“空间已满”，此上限可以通过修改配置文件等方式调整吗，谢谢。

**Comment by jamebal** [comment]
在用户管理可以修改配额

**Comment by mawanglin** [comment]
> 在用户管理可以修改配额

已找到修改，谢谢。
目前配额似乎是有上限100G对吗？我这里最大只能调整到100。
![image](https://user-images.githubusercontent.com/3214028/135373827-cf26679c-f3cf-4de5-a0b7-0f26984a7f54.png)

**Comment by jamebal** [comment]
目前是的，下个版本修复这个问题

**Comment by mawanglin** [comment]
> 目前是的，下个版本修复这个问题

明白，谢谢。
