### ISSUE TITLE
请问有milton的中文文档吗

### ISSUE THREAD

**Issue by Madao1994** [jamebal/jmal-cloud-view#17]
比如我想实现用OSS或者minIO之类的对象存储代替本地存储，milton这块儿要怎么处理

**Comment by jamebal** [comment]
milton是用来作为WebDAV服务器的(milton doc: https://milton.io/documentation/)
对象存储之类的功能需要自己另外实现

**Comment by jamebal** [comment]
通过webdav的方式访问对象存储服务器上的数据，理论上可行，但是现有的Milton做不到，得在Milton基础上扩展
