### ISSUE TITLE
大佬您好，请问下docker镜像有更新到最新吗？

### ISSUE THREAD

**Issue by mawanglin** [jamebal/jmal-cloud-view#18]
大佬您好，看你github的提交记录里面，您已修复用户最大配额只有100G的限制，但是更新您最新的容器镜像后发现还是存在配置只能最大设置到100GB，不知道是我配置文件未更新还是您还未更新阿里云上的镜像；如果您还未更新镜像请帮忙更新一下，谢谢；如果是需要调整本地配置文件，还请不吝指教；还有一个不情之请，不知是否方便将您的镜像在docker hub上也提交一份，[握手]。

**Comment by jamebal** [comment]
阿里云镜像更新了

**Comment by jamebal** [comment]
docker hub: https://hub.docker.com/repository/docker/jmal/jmalcloud

**Comment by mawanglin** [comment]
收到，非常感谢，我这里试了成都区域的阿里云，已重新pull最新的镜像，也新创建了新的容器，目前配额仍然还是最大只能设置到100GB，我换杭州或docker hub上的再试一下。

**Comment by jamebal** [comment]
系统更新了,刚才打的包有问题,我重新打包😂

**Comment by mawanglin** [comment]
怪不得，刚刚拉了docker hub上的，启动起来显示403，现在重新拉了杭州的镜像，已经可以了，感谢大佬。
![Uploading 0018A0BF.png…]()

**Comment by mawanglin** [comment]
怪不得，刚刚拉了docker hub上的，启动起来显示403，现在重新拉了杭州的镜像，已经可以了，感谢大佬。
![Uploading 0018A0BF.png…]()

**Comment by mawanglin** [comment]
怪不得，刚刚拉了docker hub上的，启动起来显示403，🤣；现在重新拉了杭州的镜像，已经可以了，感谢大佬。😊

**Comment by jamebal** [comment]
ok,所有镜像都已更新

**Comment by mawanglin** [comment]
感谢，👍🤝
