### ISSUE TITLE
普通用户使用only office服务提示无权限

### ISSUE THREAD

**Issue by virtualbsd** [jamebal/jmal-cloud-view#180]
非常感谢作者开发出这么好用的程序。在使用超级管理员登录使用only office服务能正常打开文档编辑功能，普通用户提示无权限，具体情况见图：
/
![图片1](https://github.com/jamebal/jmal-cloud-view/assets/168826580/55307afc-c1c5-4aa8-a024-daa3068bbf7e)

**Comment by jamebal** [comment]
1. 临时解决办法:  为普通用户加上修改网盘设置的权限
<img width="274" alt="截屏2024-06-12 19 15 48" src="https://github.com/jamebal/jmal-cloud-view/assets/49510841/ab221863-e3a2-40f5-8500-cdf51ee426f7">

2. 下个版本修复该问题
