### ISSUE TITLE
能否考虑接入KKfileview预览

### ISSUE THREAD

**Issue by jack-taozhang** [jamebal/jmal-cloud-view#189]
KKfileview可以预览的文件比较多，是否可以考虑设置接入KKfileview预览。

**Comment by jack-taozhang** [comment]
![image](https://github.com/jamebal/jmal-cloud-view/assets/169911019/576906eb-935e-4871-a3a4-f7938d85d806)

**Comment by jack-taozhang** [comment]
![image](https://github.com/jamebal/jmal-cloud-view/assets/169911019/593e9c1e-4dec-4db7-983e-f4d579ff9260)

**Comment by jamebal** [comment]
配置KKfileview链接, 打开文件通过外链打开吗

**Comment by jack-taozhang** [comment]
可以参照Alist里面的iframe预览。
![image](https://github.com/jamebal/jmal-cloud-view/assets/169911019/fe144ac4-ad47-4afc-9130-a7744af4a472)

**Comment by jack-taozhang** [comment]
预览效果如下图
![image](https://github.com/jamebal/jmal-cloud-view/assets/169911019/13cff33e-9e7d-430c-9626-634aa3aa7242)

**Comment by jamebal** [comment]
下个版本加上

**Comment by jack-taozhang** [comment]
是的；
Onlyoffice解决了办公文件的在线编辑功能；
KKviwer解决了文件在线预览查看功能；

**Comment by barry200890** [comment]
之前看KKviwer有些bug，不知道现在有没有修复

**Comment by jamebal** [comment]
v2.9.2 已加入预览设置
