### ISSUE TITLE
左侧导航栏 图标修改

### ISSUE THREAD

**Issue by thinkeless** [jamebal/jmal-cloud-view#19]
Hi, 请问登陆界面和左侧导航栏的图标和文字可以替换吗？谢谢🙏

**Comment by jamebal** [comment]
<img width="201" alt="截屏2021-11-15 上午9 48 11" src="https://user-images.githubusercontent.com/49510841/141709754-836857cc-dae6-44af-a432-1edb1a929f21.png">
这个吗？

**Comment by thinkeless** [comment]
![image](https://user-images.githubusercontent.com/15151547/141710078-9ad7df76-3289-4764-bbfd-f4ce10b0fd34.png)

**Comment by thinkeless** [comment]
![image](https://user-images.githubusercontent.com/15151547/141710138-e9830af1-d4be-4a6c-8bff-1e7fa245abbe.png)

**Comment by thinkeless** [comment]
Hi,  找了很多开源软件，发现您这个项目真心不错，想拿来给公司用，🙏

**Comment by jamebal** [comment]
现在不能换，下个版本出个可更换的

**Comment by thinkeless** [comment]
🙏，，期待！

**Comment by jamebal** [comment]
已添加自定义网盘logo和名称的功能
