### ISSUE TITLE
2.9.1office打开提示文档安全令牌的格式不正确

### ISSUE THREAD

**Issue by kg94666** [jamebal/jmal-cloud-view#194]
![image](https://github.com/jamebal/jmal-cloud-view/assets/153484385/80ac3d09-55ac-4acd-8e22-9dea7e1b028c)

**Comment by jamebal** [comment]
修改[docker-compose.yml](https://github.com/jamebal/jmal-cloud-server/blob/master/docker-compose.base.yml), 自行修改挂载路径和JWT_SECRET
```shell
docker-compose pull && docker-compose up -d --remove-orphans
```
启动完成后在, 在网盘设置-OnlyOffice中填入刚刚设置的密钥([docker-compose.yml](https://github.com/jamebal/jmal-cloud-server/blob/master/docker-compose.base.yml)文件的JWT_SECRET)
