### ISSUE TITLE
移动文件变成了复制

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-view#195]
在将文件从子文件夹移动到上一级文件夹的时候，选择的是移动，实际变成了复制。

**Comment by jamebal** [comment]
有提示"移动成功"吗

**Comment by kokojacket** [comment]
没有，主文件夹大小大概40G，底下两个子文件夹，一个18G一个22G左右。将两个子文件夹移动到和主文件夹平级。这个情况出现的。

**Comment by jamebal** [comment]
也没有提示失败吗

**Comment by kokojacket** [comment]
是的也没有失败提示。也可能还移动的内容比较多。我没有关注到

**Comment by jamebal** [comment]
没有提示成功,也没有提示失败, 里面的子文件多吗, 可能还在跑

**Comment by kokojacket** [comment]
是的，子文件和子文件夹多。

**Comment by kokojacket** [comment]
但是现在跑完了，出现的现象是复制。

**Comment by jamebal** [comment]
好的, 我复现一下

**Comment by kokojacket** [comment]
刚才尝试移动新的文件到上级目录，出现：
![image](https://github.com/jamebal/jmal-cloud-view/assets/74887370/3cda5cdc-e20d-4a35-9a38-ea0f2322beb8)

**Comment by kokojacket** [comment]
![image](https://github.com/jamebal/jmal-cloud-view/assets/74887370/ccb25d76-8842-4d26-8122-9dd288c773e9)
本地nasnas上操作，发现文件夹权限不足，无法写入。需要改权限。所有新生成的文件夹好像都是admin。
![image](https://github.com/jamebal/jmal-cloud-view/assets/74887370/9fd9305e-d881-4d87-9b9a-df5d0bf29160)

**Comment by kokojacket** [comment]
![recording](https://github.com/user-attachments/assets/fd1943a4-599c-495b-9e63-5e0b41b0a54e)
新版仍然出现了移动变成了复制。

**Comment by jamebal** [comment]
> ![recording](https://private-user-images.githubusercontent.com/74887370/348939310-fd1943a4-599c-495b-9e63-5e0b41b0a54e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDg1NzUsIm5iZiI6MTcyMTEwODI3NSwicGF0aCI6Ii83NDg4NzM3MC8zNDg5MzkzMTAtZmQxOTQzYTQtNTk5Yy00OTViLTllNjMtNWUwYjQxYjBhNTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA1Mzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNzk1MzhlNmExNGNjYmUxMTY5NWQ5YzkwZDhiNGI0M2NlOWJkNTBjMjUyYzllZjI0YTNjZDBkYTMxZmM2NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QcZB81VbYpjkYh3ix0_tCekh39kfIxrsaY1_cMOno5w) [ ![recording](https://private-user-images.githubusercontent.com/74887370/348939310-fd1943a4-599c-495b-9e63-5e0b41b0a54e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDg1NzUsIm5iZiI6MTcyMTEwODI3NSwicGF0aCI6Ii83NDg4NzM3MC8zNDg5MzkzMTAtZmQxOTQzYTQtNTk5Yy00OTViLTllNjMtNWUwYjQxYjBhNTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA1Mzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNzk1MzhlNmExNGNjYmUxMTY5NWQ5YzkwZDhiNGI0M2NlOWJkNTBjMjUyYzllZjI0YTNjZDBkYTMxZmM2NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QcZB81VbYpjkYh3ix0_tCekh39kfIxrsaY1_cMOno5w) ](https://private-user-images.githubusercontent.com/74887370/348939310-fd1943a4-599c-495b-9e63-5e0b41b0a54e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDg1NzUsIm5iZiI6MTcyMTEwODI3NSwicGF0aCI6Ii83NDg4NzM3MC8zNDg5MzkzMTAtZmQxOTQzYTQtNTk5Yy00OTViLTllNjMtNWUwYjQxYjBhNTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA1Mzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNzk1MzhlNmExNGNjYmUxMTY5NWQ5YzkwZDhiNGI0M2NlOWJkNTBjMjUyYzllZjI0YTNjZDBkYTMxZmM2NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QcZB81VbYpjkYh3ix0_tCekh39kfIxrsaY1_cMOno5w) [ ](https://private-user-images.githubusercontent.com/74887370/348939310-fd1943a4-599c-495b-9e63-5e0b41b0a54e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDg1NzUsIm5iZiI6MTcyMTEwODI3NSwicGF0aCI6Ii83NDg4NzM3MC8zNDg5MzkzMTAtZmQxOTQzYTQtNTk5Yy00OTViLTllNjMtNWUwYjQxYjBhNTRlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA1Mzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNzk1MzhlNmExNGNjYmUxMTY5NWQ5YzkwZDhiNGI0M2NlOWJkNTBjMjUyYzllZjI0YTNjZDBkYTMxZmM2NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QcZB81VbYpjkYh3ix0_tCekh39kfIxrsaY1_cMOno5w) 新版仍然出现了移动变成了复制。

有一个文件提示移动成功了, 这个文件只是复制了吗?

**Comment by kokojacket** [comment]
是的，并且不是一个，是3个文件复制了，剩下的都没有成功。
