### ISSUE TITLE
重新设置了转码参数之后，未转码视频不再转码了。

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-view#197]
先关闭里转码，然后等待还没有转码完成的任务完成结束之后。
重新设置了转码参数。
已经上传的视频中符合参数的视频，没有生成转码任务。

**Comment by jamebal** [comment]
已经上传过, 不会再转码了

**Comment by kokojacket** [comment]
上传后未转码但复合新的转码要求的视频，是否会转码？

**Comment by kokojacket** [comment]
那就顺带建议优化一下🤣🤣🤣
1、重新设置转码参数之后，应该重新扫描系统文件，对复合转码要求的视频文件进行转码。
2、建议右键添加一个手动转码。可以给特定视频添加转码要求。
3、建议任务进度可以手动暂停或者终止。

**Comment by jamebal** [comment]
v2.9.2已优化
