### ISSUE TITLE
搜索不支持符号

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-view#199]
![image](https://github.com/jamebal/jmal-cloud-view/assets/74887370/b79f2d0c-f905-4afa-8120-7fea2d7e2395)
![image](https://github.com/jamebal/jmal-cloud-view/assets/74887370/9f5f6efc-0de6-47d0-bd1c-d0f48d5e6de5)

**Comment by jamebal** [comment]
不支持符号, 只能是中英文字符

**Comment by kokojacket** [comment]
![image](https://github.com/jamebal/jmal-cloud-view/assets/74887370/f6a789af-b8fa-43d9-8157-31b134439b93)
重建索引的按钮，进度每次到60-70就会消失。

**Comment by kokojacket** [comment]
> 不支持符号, 只能是中英文字符

好的。🤣

**Comment by jamebal** [comment]
> ![image](https://private-user-images.githubusercontent.com/74887370/341024665-f6a789af-b8fa-43d9-8157-31b134439b93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTE4MDgsIm5iZiI6MTcxODc5MTUwOCwicGF0aCI6Ii83NDg4NzM3MC8zNDEwMjQ2NjUtZjZhNzg5YWYtYjhmYS00M2Q5LTgxNTctMzFiMTM0NDM5YjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEwMDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTA4MTk4MTJlOGM1NzI2MjhmYTY0ZWEzZWY4M2ExYWNkY2NmMmQ4MzZkYWU3ZWRkZmNiOGEzNmE3ZTMxNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k9a3a8VnoZ6RUsjmaRHUrOSnxBdTNopZsPmut_TAmTc) 重建索引的按钮，进度每次到60-70就会消失。

消失就是完成了

**Comment by HoGC** [comment]
> 不支持符号, 只能是中英文字符

以前是支持的，基于什么考虑去除了呢

**Comment by jamebal** [comment]
> > 不支持符号, 只能是中英文字符
> 
> 以前是支持的，基于什么考虑去除了呢

以前是字符匹配, 现在是分词搜索

**Comment by HoGC** [comment]
> > > 不支持符号, 只能是中英文字符
> > 
> > 
> > 以前是支持的，基于什么考虑去除了呢
> 
> 以前是字符匹配, 现在是分词搜索

那能不能做到支持多词呢，a_b好像也不能使用a b进行搜索

**Comment by jamebal** [comment]
> > > > 不支持符号, 只能是中英文字符
> > > 
> > > 
> > > 以前是支持的，基于什么考虑去除了呢
> > 
> > 
> > 以前是字符匹配, 现在是分词搜索
> 
> 那能不能做到支持多词呢，a_b好像也不能使用a b进行搜索

直接输入多个词就行了

**Comment by HoGC** [comment]
> > > > > 不支持符号, 只能是中英文字符
> > > > 
> > > > 
> > > > 以前是支持的，基于什么考虑去除了呢
> > > 
> > > 
> > > 以前是字符匹配, 现在是分词搜索
> > 
> > 
> > 那能不能做到支持多词呢，a_b好像也不能使用a b进行搜索
> 
> 直接输入多个词就行了

用什么分割词呢？我测试使用空格是不行的

**Comment by jamebal** [comment]
> > > > > > 不支持符号, 只能是中英文字符
> > > > > 
> > > > > 
> > > > > 以前是支持的，基于什么考虑去除了呢
> > > > 
> > > > 
> > > > 以前是字符匹配, 现在是分词搜索
> > > 
> > > 
> > > 那能不能做到支持多词呢，a_b好像也不能使用a b进行搜索
> > 
> > 
> > 直接输入多个词就行了
> 
> 用什么分割词呢？我测试使用空格是不行的

你输入时连在一起也没关系, 会自动分词

**Comment by HoGC** [comment]
> > > > > > > 不支持符号, 只能是中英文字符
> > > > > > 
> > > > > > 
> > > > > > 以前是支持的，基于什么考虑去除了呢
> > > > > 
> > > > > 
> > > > > 以前是字符匹配, 现在是分词搜索
> > > > 
> > > > 
> > > > 那能不能做到支持多词呢，a_b好像也不能使用a b进行搜索
> > > 
> > > 
> > > 直接输入多个词就行了
> > 
> > 
> > 用什么分割词呢？我测试使用空格是不行的
> 
> 你输入时连在一起也没关系, 会自动分词

![image](https://github.com/user-attachments/assets/f0f1d1b6-00a2-4f33-8136-8a8aabb7d883)
不行，我的版本不是最新的，应该是上个月的，是有更新？

**Comment by jamebal** [comment]
> > > > > > > > 不支持符号, 只能是中英文字符
> > > > > > > 
> > > > > > > 
> > > > > > > 以前是支持的，基于什么考虑去除了呢
> > > > > > 
> > > > > > 
> > > > > > 以前是字符匹配, 现在是分词搜索
> > > > > 
> > > > > 
> > > > > 那能不能做到支持多词呢，a_b好像也不能使用a b进行搜索
> > > > 
> > > > 
> > > > 直接输入多个词就行了
> > > 
> > > 
> > > 用什么分割词呢？我测试使用空格是不行的
> > 
> > 
> > 你输入时连在一起也没关系, 会自动分词
> 
> ![image](https://private-user-images.githubusercontent.com/50402699/348164742-f0f1d1b6-00a2-4f33-8136-8a8aabb7d883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3Njk2ODUsIm5iZiI6MTcyMDc2OTM4NSwicGF0aCI6Ii81MDQwMjY5OS8zNDgxNjQ3NDItZjBmMWQxYjYtMDBhMi00ZjMzLTgxMzYtOGE4YWFiYjdkODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA3Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MGU0YWY1MjE0OWQ5ZmU0OWU3YWIzZTQxZjgyOTU1MGZiZWFlOWI2MGYwOGQ1NjE3ODE0MDQ0OTJlOGYyYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jg0Q4mpaWIi5yC2z5tylvLIM1IoPW_Z-11-CtwnbA64) 不行，我的版本不是最新的，应该是上个月的，是有更新？

下个版本优化下, 加入特殊符号的搜索
