### ISSUE TITLE
转码参数未生效

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-view#200]
![Clip_2024-06-19_19-54-29](https://github.com/jamebal/jmal-cloud-view/assets/74887370/b8b80173-cf73-4a35-a0cc-c3598ad47a6e)
![Clip_2024-06-19_19-55-19](https://github.com/jamebal/jmal-cloud-view/assets/74887370/37bac39e-267b-4ee1-8630-b83eacacda09)
![Clip_2024-06-19_19-55-30](https://github.com/jamebal/jmal-cloud-view/assets/74887370/ea6054dc-6790-4e83-b509-8c05d0ebfa9d)

**Comment by jamebal** [comment]
看截图, 是禁用转码了

**Comment by kokojacket** [comment]
如果我启用转码，然后删除为转码的视频，重新在主机中移动视频到file文件夹的用户下。是否会触发转码

**Comment by kokojacket** [comment]
重新部署了jma，先设置了转码参数，导入视频仍然不转码
![Clip_2024-06-19_20-12-37](https://github.com/jamebal/jmal-cloud-view/assets/74887370/34fce324-1949-4af1-8790-2682e5876bc1)
![Clip_2024-06-19_20-13-51](https://github.com/jamebal/jmal-cloud-view/assets/74887370/be135896-33e6-429f-8e76-27b1c742823b)
![Clip_2024-06-19_20-14-03](https://github.com/jamebal/jmal-cloud-view/assets/74887370/f2c6043c-8473-4871-8d12-34fda09b5c88)

**Comment by jamebal** [comment]
> 如果我启用转码，然后删除为转码的视频，重新在主机中移动视频到file文件夹的用户下。是否会触发转码

会

**Comment by jamebal** [comment]
目前是这样, 下个版本优化下, 满足其一即可

**Comment by kokojacket** [comment]
> 目前是这样, 下个版本优化下, 满足其一即可

我就说怎么无论如何也转码不了🤣

**Comment by jamebal** [comment]
v2.9.2已优化
