### ISSUE TITLE
服务器占用非常高咋处理啊？

### ISSUE THREAD

**Issue by seanzhui** [jamebal/jmal-cloud-view#206]
![6C365374-47AF-4255-ABA0-8A06DCCD7B95](https://github.com/jamebal/jmal-cloud-view/assets/26628514/6cff0009-1eda-4bdf-b206-3600711d33c0)

**Comment by jamebal** [comment]
纯cpu视频转码非常耗资源

**Comment by jamebal** [comment]
下个版本优化下, 可配置同时转码的数量

**Comment by jamebal** [comment]
v2.9.2可配置同时转码的数量
