### ISSUE TITLE
配置有误 或者 Access Key 没有权限

### ISSUE THREAD

**Issue by seanzhui** [jamebal/jmal-cloud-view#209]
![1719295537066_7452F88A-91EE-4295-9DF7-FD3A7C643512](https://github.com/jamebal/jmal-cloud-view/assets/26628514/40f34993-87c7-44df-bf2e-1e2e641bde64)

切换到阿里云oss的时候，错误抛出此错误，配置是 没有问题的，都是在正常使用的，有点奇怪这个抛出怎么处理？

**Comment by jamebal** [comment]
我这边先复现一下

**Comment by seanzhui** [comment]
> 我这边先复现一下

有复现嘛？

**Comment by jamebal** [comment]
无法复现, 请确保这四个参数没有问题: Endpoint, Access Key, Secret Key, Bucket

**Comment by jamebal** [comment]
或者查看日志看具体是什么问题: `docker logs -f jmalcloud_server`
