### ISSUE TITLE
不支持armv8吗

### ISSUE THREAD

**Issue by walterfang1209** [jamebal/jmal-cloud-view#211]
我rtd1296的ds218运行会报以下错：
![屏幕截图 2024-06-29 202942](https://github.com/jamebal/jmal-cloud-view/assets/109520056/03c1951b-d7b5-4c23-88fa-4f61d09b74b1)

**Comment by walterfang1209** [comment]
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by jamebal** [comment]
这是用的阿里云的镜像吗

**Comment by walterfang1209** [comment]
> 这是用的阿里云的镜像吗

用的docker-compose.base-aliyun-beijing.yml里的内容，只是文件名改成了docker-compose.base.yml

**Comment by jamebal** [comment]
修改`docker-compose`, 在镜像名后面加上后缀`-arm64`: https://github.com/jamebal/jmal-cloud-view/issues/177#issuecomment-2165860292

**Comment by walterfang1209** [comment]
现报如下错误：
![屏幕截图 2024-06-30 101418](https://github.com/jamebal/jmal-cloud-view/assets/109520056/ff10f67a-aa14-483b-8e30-0fb7a3157630)

**Comment by walterfang1209** [comment]
现报如下错误：
![屏幕截图 2024-06-30 102434](https://github.com/jamebal/jmal-cloud-view/assets/109520056/78fa9932-c72e-4576-9fdd-40eea51ee8b2)

**Comment by jamebal** [comment]
手动创建目录试试: `mkdir -p /volumel/WorkDir/docker/jmalcloud/mongodb/data/db`

**Comment by walterfang1209** [comment]
> 手动创建目录试试: `mkdir -p /volumel/WorkDir/docker/jmalcloud/mongodb/data/db`

试过了，这个是无底洞，创建一个缺失的目录后又会提示有其他目录缺失

**Comment by jamebal** [comment]
是提示缺少这个吗: `../jmalcloud/mongodb/backup`

**Comment by walterfang1209** [comment]
> 是提示缺少这个吗: `../jmalcloud/mongodb/backup`

`/volume1/WorkDir/docker`这个文件夹就不存在

**Comment by jamebal** [comment]
或者修改docker-compose.yml, 把里面的挂载路径改成绝对路径试试

**Comment by walterfang1209** [comment]
```
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db
      - ./docker/jmalcloud/mongodb/backup:/dump
```
这两个路径是可以随自己定的吗？

**Comment by jamebal** [comment]
左边的改成自己系统里的目录, 右边的不能改

**Comment by walterfang1209** [comment]
> 左边的改成自己系统里的目录, 右边的不能改

好的

**Comment by walterfang1209** [comment]
我对`docker-compose.yml`进行了如下修改，并确保两个目录确实已经创建，现在报以下错误：
![屏幕截图 2024-06-30 113234](https://github.com/jamebal/jmal-cloud-view/assets/109520056/310495af-c05c-4415-ad5e-edef35818ec8)
![屏幕截图 2024-06-30 113209](https://github.com/jamebal/jmal-cloud-view/assets/109520056/ad299972-f775-4fab-ac45-64a81ea9910a)

**Comment by jamebal** [comment]
看看mongodb的日志: `docker logs -f  jmalcloud_mongodb`

**Comment by walterfang1209** [comment]
> 看看mongodb的日志: `docker logs -f jmalcloud_mongodb`
好像是说版本不够？
```
WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
  applies to all versions ≥5.0, any of 4.4 ≥4.4.19
  see https://jira.mongodb.org/browse/SERVER-71772
  see https://jira.mongodb.org/browse/SERVER-55178
  see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306
```

**Comment by jamebal** [comment]
需要把mongodb的镜像换成4.4.18或之前的版本: `mongo:4.4.18`, 这个镜像在docker hub上

**Comment by walterfang1209** [comment]
> 需要把mongodb的镜像换成4.4.18或之前的版本: `mongo:4.4.18`, 这个镜像在docker hub上

好的，我也有自己的阿里容器，可以直接拉去，我再拉取一下试试。
感谢大佬耐心指点🙏

**Comment by jamebal** [comment]
或者直接用这个:`docker.jmalx.com/library/mongo:4.4.18`

**Comment by walterfang1209** [comment]
> 或者直接用这个:`docker.jmalx.com/library/mongo:4.4.18`

这个貌似没有arm64?
![屏幕截图 2024-06-30 114929](https://github.com/jamebal/jmal-cloud-view/assets/109520056/bcf061dd-91eb-452f-af99-f3020b6beb21)

**Comment by jamebal** [comment]
> > 或者直接用这个:`docker.jmalx.com/library/mongo:4.4.18`
> 
> 这个貌似没有arm64? ![屏幕截图 2024-06-30 114929](https://private-user-images.githubusercontent.com/109520056/344442285-bcf061dd-91eb-452f-af99-f3020b6beb21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTk4NDgsIm5iZiI6MTcxOTcxOTU0OCwicGF0aCI6Ii8xMDk1MjAwNTYvMzQ0NDQyMjg1LWJjZjA2MWRkLTkxZWItNDUyZi1hZjk5LWYzMDIwYjZiZWIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwMzUyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjQxNDI1ZTk1ZDM0ZWE5OTY3N2QxOTMwMjYwODA1MzJiZmIyY2UwNGQ2ZTJiNjBkYjNkZWI2YzM5MjlmNGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sOmIv1w0nQI8TNGyKz9upZT1Gl4YFAeb00gVFwt6zxU)

这个是在docker hub上的, 把后边的`-arm64`去掉就行

**Comment by walterfang1209** [comment]
> > > 或者直接用这个:`docker.jmalx.com/library/mongo:4.4.18`
> > 
> > 
> > 这个貌似没有arm64? ![屏幕截图 2024-06-30 114929](https://private-user-images.githubusercontent.com/109520056/344442285-bcf061dd-91eb-452f-af99-f3020b6beb21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTk4NDgsIm5iZiI6MTcxOTcxOTU0OCwicGF0aCI6Ii8xMDk1MjAwNTYvMzQ0NDQyMjg1LWJjZjA2MWRkLTkxZWItNDUyZi1hZjk5LWYzMDIwYjZiZWIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwMzUyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjQxNDI1ZTk1ZDM0ZWE5OTY3N2QxOTMwMjYwODA1MzJiZmIyY2UwNGQ2ZTJiNjBkYjNkZWI2YzM5MjlmNGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sOmIv1w0nQI8TNGyKz9upZT1Gl4YFAeb00gVFwt6zxU)
> 
> 这个是在docker hub上的, 把后边的`-arm64`去掉就行

又是这个报错，我再手动添加相应目录试试
![屏幕截图 2024-06-30 115604](https://github.com/jamebal/jmal-cloud-view/assets/109520056/f027b349-1c2d-41f7-b978-2397160679b1)

**Comment by walterfang1209** [comment]
现在部署完成了，但是登不上去
![GIF 2024-6-30 12-08-19](https://github.com/jamebal/jmal-cloud-view/assets/109520056/a7aff95f-e4fa-462b-b8d2-064fdb9705c1)

**Comment by jamebal** [comment]
看看jmalcloud_server的日志: `docker logs -f  jmalcloud_server`

**Comment by walterfang1209** [comment]
> 看看jmalcloud_server的日志: `docker logs -f jmalcloud_server`

![Uploading 屏幕截图 2024-06-30 121243.png…]()

**Comment by walterfang1209** [comment]
> 看看jmalcloud_server的日志: `docker logs -f jmalcloud_server`

![屏幕截图 2024-06-30 121243](https://github.com/jamebal/jmal-cloud-view/assets/109520056/ee9fa259-9d56-42c5-9eac-1e1a953a013c)

**Comment by jamebal** [comment]
把jmalcloud的镜像换成这个试试: `docker.jmalx.com/jmal/jmalcloud`

**Comment by walterfang1209** [comment]
> 把jmalcloud的镜像换成这个试试: `docker.jmalx.com/jmal/jmalcloud`

最后要加`-arm64`吗

**Comment by jamebal** [comment]
> > 把jmalcloud的镜像换成这个试试: `docker.jmalx.com/jmal/jmalcloud`
> 
> 最后要加`-arm64`吗

不用加

**Comment by jamebal** [comment]
使用这个命令看看其他镜像对不对: `docker images | grep "jmalcloud"`

**Comment by walterfang1209** [comment]
好像说我`pull`太多了，还有命令运行结果如下：
![屏幕截图 2024-06-30 122301](https://github.com/jamebal/jmal-cloud-view/assets/109520056/1c98eb5e-5345-44e9-a50e-6a0d6f2394ce)

**Comment by jamebal** [comment]
稍等一下, 或者用这个: `registry.cn-guangzhou.aliyuncs.com/jmalcloud/jmalcloud:latest-arm64`

**Comment by walterfang1209** [comment]
![屏幕截图 2024-06-30 124341](https://github.com/jamebal/jmal-cloud-view/assets/109520056/4f6acb37-91f9-4f98-9074-0d5ec529587b)
![Uploading 屏幕截图 2024-06-30 124400.png…]()

**Comment by walterfang1209** [comment]
![屏幕截图 2024-06-30 124400](https://github.com/jamebal/jmal-cloud-view/assets/109520056/c1787143-c6df-40ab-88eb-6fb29bff4855)
![屏幕截图 2024-06-30 124341](https://github.com/jamebal/jmal-cloud-view/assets/109520056/72f36ba1-21a0-4a88-a27b-db771e7aeb99)

**Comment by jamebal** [comment]
刚才启动失败的有些影响, 把之前的都删掉重新跑一边
1. 停止docker-compose
```shell
docker-compose down
```
2. 删除mongodb和jmalcloud_server的挂载目录

3. 重新启动
```shell
docker-compose up -d
```

**Comment by walterfang1209** [comment]
第二步具体怎么操作？

**Comment by jamebal** [comment]
> 第二步具体怎么操作？

docker-compose.yml文件中的所有的挂载目录: 
```shell
    volumes:
      - /volume1/docker/jmalcloud/mongodb/data/db:/data/db
      - /volume1/docker/jmalcloud/mongodb/backup:/dump
    ...省略
    volumes:
      - /volume1/docker/jmalcloud/files:/jmalcloud/files/
```

如果是这样的就删除目录: `rm -rf /volume1/docker/jmalcloud`

**Comment by walterfang1209** [comment]
部署成功，感谢大佬帮助。
issue can be closed.
