### ISSUE TITLE
搜索不到文件

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-view#228]
![Clip_2024-07-10_13-28-49](https://github.com/jamebal/jmal-cloud-view/assets/74887370/7aae188d-a5af-4b5b-b499-68834b6b6cdc)
![Clip_2024-07-10_13-29-25](https://github.com/jamebal/jmal-cloud-view/assets/74887370/bb9e0ec8-3c98-4395-8dc0-f999bd100e5b)

**Comment by jamebal** [comment]
对文件重建索引试试

**Comment by jamebal** [comment]
其他文件能搜索到吗, 还是特定的一些文件搜索不到

**Comment by kokojacket** [comment]
![Clip_2024-07-10_14-15-21](https://github.com/jamebal/jmal-cloud-view/assets/74887370/f9cad542-f20d-4360-a249-f0a0f810cfa2)
jin'du进度条不动

**Comment by kokojacket** [comment]
重建索引搜索到了
