### ISSUE TITLE
v2.9.2 建议优化点

### ISSUE THREAD

**Issue by jack-taozhang** [jamebal/jmal-cloud-view#229]
云盘的功能越来好。新增加的iframe预览配置，可以很方便的接入KKfileview，建议做以下优化调整；
1、不弹出预览时背景色是否可以调整为不透明；
![image](https://github.com/jamebal/jmal-cloud-view/assets/169911019/f210e501-8427-4d6c-b53f-bddba73ec76e)
2、文件的后缀名是否可以不用区分大小写；(目前需要和iframe里面的文件后缀大小写一样）；
![image](https://github.com/jamebal/jmal-cloud-view/assets/169911019/26178bd5-5bec-4bc2-8d84-1b9c932f8638)

**Comment by jamebal** [comment]
下个版本加上
