### ISSUE TITLE
v2.9.2 用户管理修改容量后，页面使用容量图标不显示

### ISSUE THREAD

**Issue by BigBangz** [jamebal/jmal-cloud-view#239]
作者你好，用户管理修改容量后，页面使用容量图标不显示。
重启服务后也是一样
![image](https://github.com/user-attachments/assets/c28ae1d3-6ee6-4d47-9955-2d85fc6b6cd5)
![image](https://github.com/user-attachments/assets/c52162c1-fc2b-4f73-810a-7930f6123376)

**Comment by jamebal** [comment]
上传文件后有显示了

**Comment by BigBangz** [comment]
上传文件后正常显示， 感谢

**Comment by BigBangz** [comment]
上传文件后正常显示， 感谢

**Comment by BigBangz** [comment]
上传文件后正常显示， 感谢
