### ISSUE TITLE
minio 文件过大会丢失文件

### ISSUE THREAD

**Issue by fengjunjun98** [jamebal/jmal-cloud-view#259]
集成minio后文件超过5G,服务器的minio文件只是显示4.9G 10G也是4.9G,上次的文件下载后文件有很大的丢失!

麻烦作者看看解决一下 @jamebal

**Comment by jamebal** [comment]
感谢反馈, 我这边先测试一下

**Comment by jamebal** [comment]
v2.10.0已修复
