### ISSUE TITLE
新建了一个jmalcloud为什么博客页变这样了

### ISSUE THREAD

**Issue by kg94666** [jamebal/jmal-cloud-view#260]
![微信图片_20240807111913](https://github.com/user-attachments/assets/c08fe2c8-9ff1-4433-9f0f-970e75caed44)

**Comment by jamebal** [comment]
网盘地址和博客地址分别是什么样的

**Comment by jamebal** [comment]
最新版本博客地址为: 网盘地址 + /blog
例如: 网盘地址为: http://127.0.0.1:7070, 则博客地址为: http://127.0.0.1:7070/blog

**Comment by kg94666** [comment]
> 最新版本博客地址为： 网盘地址 + /blog 例如： 网盘地址为： http://127.0.0.1:7070， 则博客地址为： http://127.0.0.1:7070/blog

还是这样
![11](https://github.com/user-attachments/assets/7761dfa9-f768-44f0-8602-8e841dd0b2fb)

**Comment by jamebal** [comment]
是最新版本吗

**Comment by jamebal** [comment]
<img width="557" alt="截屏2024-08-07 11 38 49" src="https://github.com/user-attachments/assets/e2e82f62-f828-48fb-bcfb-5bf3422d4288">
在这里填入博客地址试试

**Comment by kg94666** [comment]
> <img alt="截屏2024-08-07 11 38 49" width="557" src="https://private-user-images.githubusercontent.com/49510841/355666641-e2e82f62-f828-48fb-bcfb-5bf3422d4288.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDI1MDgsIm5iZiI6MTcyMzAwMjIwOCwicGF0aCI6Ii80OTUxMDg0MS8zNTU2NjY2NDEtZTJlODJmNjItZjgyOC00OGZiLWJjZmItNWJmMzQyMmQ0Mjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAzNDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YzliMjgxNTExNjNmNzNkYTk2YjFmYWY4ZDdhYzE3MjZjYmU4YTkwMTY4YzA1ODIxNDAwZTU4OTdkMzM2MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u5J5zOcAmASlVOIZGxp8dtvABFVBSpUoV62ZXUb6TuQ">在这里填入博客地址试试

ok，填入地址后好了，谢谢
