### ISSUE TITLE
windows环境下使用docker-desktop尝试部署项目，提示安装失败

### ISSUE THREAD

**Issue by RogerLi294014** [jamebal/jmal-cloud-view#265]
![image](https://github.com/user-attachments/assets/234632ae-528d-407f-bde1-3d552251d103)
会在这里转圈转上很久（20分钟左右），然后报下面的错，要联系开发者
![Dingtalk_20240822113227](https://github.com/user-attachments/assets/d199cb19-c5fc-4dee-baef-4b508999765c)
环境背景：
![Dingtalk_20240822112716](https://github.com/user-attachments/assets/8b20b418-85fb-46f5-9c82-c924dfc72364)
![Dingtalk_20240822112734](https://github.com/user-attachments/assets/64ce90d8-5d9f-468b-a251-87193bae7acd)
![Dingtalk_20240822112758](https://github.com/user-attachments/assets/b1f37b9b-4ca9-43a9-ba03-16e5dc4957a6)

**Comment by jamebal** [comment]
不使用一键脚本, 直接使用[docker-compose.yaml](https://github.com/jamebal/jmal-cloud-server/blob/master/docker-compose.base.yml)部署

**Comment by jamebal** [comment]
或者使用阿里云的镜像: https://github.com/jamebal/jmal-cloud-server/blob/master/docker-compose.base-aliyun-beijing.yml
