### ISSUE TITLE
重启了一次机器后提示mongodb is unhealthy

### ISSUE THREAD

**Issue by kg94666** [jamebal/jmal-cloud-view#269]
我是unraid系统用compose部署，运行了很长一段时间都很好，重启了一次机器后无论怎么都up不起来
![微信图片_20240906095339](https://github.com/user-attachments/assets/9f8f9d55-9039-4391-bb97-36f593ed5998)

**Comment by jamebal** [comment]
看看mongodb的日志: 
```shell
docker logs jmalcloud_mongodb
```
