### ISSUE TITLE
ldap的账号没法添加uid字段

### ISSUE THREAD

**Issue by sansi98h** [jamebal/jmal-cloud-view#271]
例如管理员账号模式为 uid=root,cn=users,dc=aaa,dc=bbb，会提示
![image](https://github.com/user-attachments/assets/8cffe9c6-f46a-4ea1-bc7d-01186db5b563)

但是这样的字段是合法的，使用**LDAPSoft Ldap Browser 6.10**进行验证
![image](https://github.com/user-attachments/assets/96e5f40e-fae8-4c4d-9ac0-28510b63cdbc)
其他应用
![image](https://github.com/user-attachments/assets/853f23dc-6803-4ef8-83f6-cbe5b68e699d)

**Comment by elarbor** [comment]
密码是啥？

![Image](https://github.com/user-attachments/assets/42702466-e864-40f7-b5a1-ceefd2ba1899)
