### ISSUE TITLE
office文档无法查看，提示下载

### ISSUE THREAD

**Issue by fengdu126** [jamebal/jmal-cloud-view#276]
查控制台显示502，docker安装直接ip地址访问的
![image](https://github.com/user-attachments/assets/b2fc3850-4f32-439d-917c-52b712772d42)
![image](https://github.com/user-attachments/assets/c7d7c4c8-d416-4aad-9b49-3dba0bece65b)

**Comment by fengdu126** [comment]
docker配置文件没有改过，查服务都成功启动了，请问下，这个onlyoffice还需要什么特别配置才行吗
![image](https://github.com/user-attachments/assets/4ee8584f-f195-4625-bc9e-1705c28365d1)

**Comment by fengdu126** [comment]
另外，如果内置的onlyoffice无法使用的话，能否把onlyoffice去掉，试过了在ngnix配置里面去掉onlyoffice，但显示nginx启动失败

**Comment by yang478** [comment]
> 另外，如果内置的onlyoffice无法使用的话，能否把onlyoffice去掉，试过了在ngnix配置里面去掉onlyoffice，但显示nginx启动失败
我也发现这个，我在compose里去掉onlyoffice就起不来
