### ISSUE TITLE
博客问题

### ISSUE THREAD

**Issue by xiaoshun111** [jamebal/jmal-cloud-view#281]
![image](https://github.com/user-attachments/assets/9a1e7e75-10ad-443b-b068-66a0a4ab6d40)
![image](https://github.com/user-attachments/assets/faaf56f0-e270-4de6-8dd9-3da329c36d89)

样式全丢失了，无法使用

**Comment by jamebal** [comment]
访问地址是怎样的?
应该是: http://ip:7070/blog

**Comment by xiaoshun111** [comment]
http://ip:7070/blog 这个不行
http://ip:7071/blog 也不行
http://ip:7071/ 也不行
资源请求 http://ip:7070/null/layui/css/layui.css

**Comment by xiaoshun111** [comment]
部署了三个服务器都是这样

**Comment by jamebal** [comment]
在博客外观设置中填入站点地址

**Comment by xiaoshun111** [comment]
![image](https://github.com/user-attachments/assets/c9241603-83dd-4b0a-a20f-cfb883b7872d)
![image](https://github.com/user-attachments/assets/69637495-5d79-4753-9f57-17e6a9c1c52e)

我是这样填写的，但还是不行

**Comment by jamebal** [comment]
<img width="515" alt="截屏2024-09-20 17 53 10" src="https://github.com/user-attachments/assets/4b5e18db-b52b-4ddc-b300-a07a3ee9f579">
这个地址填了吗

**Comment by xiaoshun111** [comment]
可以了，谢谢

**Comment by xiaoshun111** [comment]
怎么赞赏啊

**Comment by jamebal** [comment]
点个star就行
