### ISSUE TITLE
新手遇到问题，求助,已阅读文档无果

### ISSUE THREAD

**Issue by woeoio** [jamebal/jmal-cloud-view#284]
![7a681363-5d96-42ae-ba0e-0660be900959](https://github.com/user-attachments/assets/338e8549-9805-4390-b24d-5aab1763420b)
![1a33629d-4e30-4c18-8813-1945445d4416](https://github.com/user-attachments/assets/1d4852a3-61df-4c84-a96b-79c3a0e451cb)
已通过授权令牌配置,,,并重启过 docker 容器,,,但依然提示令牌不对,

![36d7ae34-9e27-4d65-9561-169852fdec90](https://github.com/user-attachments/assets/2b1480fe-42cc-4441-85ca-1aca39f7a491)

**Comment by sansi98h** [comment]
office那个是填你dockers的JWT_SECRET的值
![image](https://github.com/user-attachments/assets/a7da20a2-f567-4239-82b2-0ee4be4c0597)

**Comment by woeoio** [comment]
> office那个是填你dockers的JWT_SECRET的值 ![image](https://private-user-images.githubusercontent.com/32392758/369590105-a7da20a2-f567-4239-82b2-0ee4be4c0597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTgxMTgsIm5iZiI6MTcyNjkxNzgxOCwicGF0aCI6Ii8zMjM5Mjc1OC8zNjk1OTAxMDUtYTdkYTIwYTItZjU2Ny00MjM5LTgyYjItMGVlNGJlNGMwNTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDExMjMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MjMzYzZlMjE2ZWU2YWIzYjJmMDBmMzNmM2VjNjBhNjY2ZTU5YjdhM2JlNDE2ZWFjZmFmN2VjZWYzZGYwYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7ZQ-ut44Nlc_AKJPfoiLOJZNYGbcoEUhk2MSx5Gwe-Q)

感谢大佬,已解决.是我粗心了
