### ISSUE TITLE
我想往网页嵌入js代码，该怎么实现

### ISSUE THREAD

**Issue by sansi98h** [jamebal/jmal-cloud-view#291]
不想修改html文件，如果应用更新可能会还原，目前是使用nginx实现

```
sub_filter '</head>' '<script async src="http://xx.com/agent.js"></script></head>';
sub_filter_once on;
```

**Comment by jamebal** [comment]
用途是什么

**Comment by sansi98h** [comment]
统计用

**Comment by jamebal** [comment]
这样也行

**Comment by sansi98h** [comment]
如果请求量太多的话nginx可能顶不住

**Comment by sansi98h** [comment]
哪个页面不知道，nginx的话，是加到body里面，相当于每一个请求都会判断一次

**Comment by jamebal** [comment]
nginx也可通过CSP在响应头中加入js脚本

**Comment by jamebal** [comment]
如果使用sub_filter 的话, 可以指定MIME 类型, 由于vue应用只有一个html, 所有不会频繁请求
```nginx
# 确保子过滤器生效，仅对 text/html 类型应用
sub_filter_types text/html;
```

**Comment by jamebal** [comment]
<img width="513" alt="截屏2024-09-26 17 26 08" src="https://github.com/user-attachments/assets/5c56377b-1003-4469-a9b9-938befc095fd">
这里可以加上这个功能

**Comment by sansi98h** [comment]
你说的是我把js代码放进去还是以后添加上这个功能，如果放js代码咋放，这个不是文本吗

我的js代码类似这种

```
<script async defer src="https://XXXXXXX/tracker.js" data-website-id="XXXXXXXXXXXX"></script>
```

**Comment by jamebal** [comment]
加个自定义页脚html的功能
