### ISSUE TITLE
JmalCloud API在哪

### ISSUE THREAD

**Issue by gjhlmy** [jamebal/jmal-cloud-view#295]
JmalCloud API在哪

**Comment by Xiaoph123** [comment]
> JmalCloud API在哪
你在启动项目的时候会看到api的地址
![image](https://github.com/user-attachments/assets/8911f9d8-2af2-412b-8f7f-b3e1b554dc73)

**Comment by jamebal** [comment]
直接使用docker-compose.yml安装: 
[JmalCloud API](https://jmalcloud.github.io/guide/installation.html#%E7%BD%91%E7%9B%98api%E5%9C%B0%E5%9D%80)
