### ISSUE TITLE
打开office文档提示文档安全令牌问题

### ISSUE THREAD

**Issue by HZJprince** [jamebal/jmal-cloud-view#297]
打开office文件提示文档安全令牌的gesh格式不正确，请问这个如何配置？
![微信截图_20241021105530](https://github.com/user-attachments/assets/2f8dd257-abb5-4fd6-b5b8-3ac856a23da1)

**Comment by jamebal** [comment]
https://jmalcloud.github.io/guide/aq/office-502.html#_2-%E6%96%87%E6%A1%A3%E5%AE%89%E5%85%A8%E4%BB%A4%E7%89%8C%E7%9A%84%E6%A0%BC%E5%BC%8F%E4%B8%8D%E6%AD%A3%E7%A1%AE%E8%AF%B7%E4%B8%8E%E6%82%A8%E7%9A%84%E6%96%87%E6%A1%A3%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%AE%A1%E7%90%86%E5%91%98%E8%81%94%E7%B3%BB%E3%80%82

**Comment by HZJprince** [comment]
谢谢指导
