### ISSUE TITLE
jmal配置外部onlyoffice,文档提示无法保存！

### ISSUE THREAD

**Issue by catbei2020** [jamebal/jmal-cloud-view#298]
大佬，jmal配置外部onlyoffice时，打开文档提示无法保存错误，如图：这个一般问题出在哪里呢？

![QQ截图20241024135154](https://github.com/user-attachments/assets/7a0b7d8e-045a-4c3c-a2e3-db76ca266e0a)

**Comment by jamebal** [comment]
外部的onlyoffice server 和 jmalcloud server两者之间需要可以相互访问

**Comment by catbei2020** [comment]
嗯嗯，双向通讯没有问题

**Comment by catbei2020** [comment]
已经解决了，谢谢！目前有个问题还想请教你一下，如何设置pdf文档默认用only打开了。

**Comment by jamebal** [comment]
目前无法设置pdf用only打开, 后续版本可以加上

**Comment by catbei2020** [comment]
期待更新

**Comment by jacktpy** [comment]
我也提示这个，请问您是怎么设置的？
