### ISSUE TITLE
关键字搜索功能疑问

### ISSUE THREAD

**Issue by HZJprince** [jamebal/jmal-cloud-view#316]
请问下，关键字搜索栏，是否可以同时匹配多个关键字？

**Comment by jamebal** [comment]
目前是有的

**Comment by HZJprince** [comment]
哦，请问下这个同时匹配多关键字，在搜索栏需要如何输入才能匹配成功？用空格分开关键字还是用逗号还是分号之类的？

**Comment by jamebal** [comment]
同时匹配多关键字适用于文件内容，不适用与文件名称
用空格分开关键字就行
