### ISSUE TITLE
WebDav传输文件有大小限制吗？

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#327]
如题，使用webdav传一些大的文件会提示如下报错，如果有大小设置我该怎么配置
![image](https://github.com/user-attachments/assets/74469ebd-4815-4c86-9914-a6457577bd87)
![image](https://github.com/user-attachments/assets/35475a22-bb71-480f-9628-aaa443131aeb)

**Comment by jamebal** [comment]
应该是没有限制, 用RaiDrive试试

**Comment by jamebal** [comment]
Windows的自带的文件资源管理器和Mac的Finder连接WebDAV都有些奇奇怪怪的问题

**Comment by 0917python** [comment]
使用webdav传一些大的文件会提示上面的报错，发现这个大小设置是受到nginx镜像中，nginx.conf的限制。在docker-compose.yml中添加：volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      并修改里面的client_max_body_size参数后，没有报错了。
不太明白为什么直接用前端不受这个限制，用webdav连接就会受到这个限制？

**Comment by jamebal** [comment]
> 使用webdav传一些大的文件会提示上面的报错，发现这个大小设置是受到nginx镜像中，nginx.conf的限制。在docker-compose.yml中添加：volumes: - ./nginx.conf:/etc/nginx/nginx.conf:ro 并修改里面的client_max_body_size参数后，没有报错了。 不太明白为什么直接用前端不受这个限制，用webdav连接就会受到这个限制？

1. 直接使用WebDAV确实会受到nginx的限制，如果是内网连接可以绕过nginx直接连接server端，server端的webdav地址为：http://{ip}:7072/webDAV/{username}, 
2. 直接用前端不受这个限制是因为前端把文件分片了，每个分片都比较小

**Comment by 0917python** [comment]
通过http://{ip}:7070/webDAV/{username},方式用WINSCP连接的，还是有受client_max_body_size大小限制。

**Comment by jamebal** [comment]
<img width="589" alt="截屏2024-12-05 11 39 09" src="https://github.com/user-attachments/assets/157b2c0c-ba09-480f-aaa1-2e88f26300f7">
使用这个端口，直连webDAV server

**Comment by 0917python** [comment]
> <img alt="截屏2024-12-05 11 39 09" width="589" src="https://private-user-images.githubusercontent.com/49510841/392644548-157b2c0c-ba09-480f-aaa1-2e88f26300f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzAzMjEsIm5iZiI6MTczMzM3MDAyMSwicGF0aCI6Ii80OTUxMDg0MS8zOTI2NDQ1NDgtMTU3YjJjMGMtYmEwOS00ODBmLWFhYTEtMmU4OGYyNjMwMGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDAzNDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNWI3MDUzZDc2NDVkMTgwMzM0ZWQ4ZDliMWI5NzNlZGM3Nzg3M2YwMGE4Mzg0MTNhMTM0NDI3ODU4ZDlkMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BnnpAFfHGU-JcEW0vKGlqoA8hkFwfBrAh1HHaWxYyQg"> 使用这个端口，直连webDAV server

nginx:
    container_name: jmalcloud_nginx
    image: registry.cn-beijing.aliyuncs.com/jmalcloud/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
