### ISSUE TITLE
索引和LDAP问题

### ISSUE THREAD

**Issue by sansi98h** [jamebal/jmal-cloud-view#328]
https://github.com/jamebal/jmal-cloud-view/issues/271#issue-2515648724

这个ldap的base dn格式还是不对

![image](https://github.com/user-attachments/assets/753c7196-dbb0-4140-a7f7-63c7dbee4481)

索引也还是会卡住
![image](https://github.com/user-attachments/assets/ae06ae0a-0558-4b8c-8e72-04caaf263e09)

不确定是哪儿的问题，应该是很多视频卡住了，因为视频的那个文件夹大小不对，也缺文件，视频转码也关闭了，**视频的文件名和路径可能有点长**

部分日志
![image](https://github.com/user-attachments/assets/bf4a7c5c-22e9-4536-8fd3-125df6bc98c1)
![image](https://github.com/user-attachments/assets/1f4854f5-6c4b-4a94-a22b-4a253af3ca74)

![image](https://github.com/user-attachments/assets/3fb546e3-1b62-4db0-82f2-e3e8ad07d885)

![image](https://github.com/user-attachments/assets/c91a2385-153e-4837-b229-9fe308a62d7a)

**Comment by jamebal** [comment]
重建索引卡住的问题: JVM_OPTS改为这样试试
```yml
      JVM_OPTS: "-Xms256m -Xmx2048m"
```
<img width="566" alt="截屏2024-12-02 19 08 40" src="https://github.com/user-attachments/assets/65ef035d-fc63-4afc-9606-a982b5822fea">

**Comment by sansi98h** [comment]
```
      TZ: "Asia/Shanghai"
      JVM_OPTS: "-Xms1024m -Xmx2048m"
```
我一直是这么多，要改成和你一样吗

**Comment by jamebal** [comment]
改成4096m试试
```yaml
      JVM_OPTS: "-Xms256m -Xmx4096m"
```

**Comment by sansi98h** [comment]
改成4096还是会卡，日志dao'zhe到这就不动
![image](https://github.com/user-attachments/assets/e9b68d5e-4383-48cb-9e82-d76c0ca3b1f2)

**Comment by jamebal** [comment]
还是卡在视频的那个文件夹吗，里面大概有多少个视频

**Comment by sansi98h** [comment]
感觉是，因为只选择视频文件夹重建就会卡，视频很多，可能上千个，大的可能几个G，时长几个小时，小的可能就几M，几分钟，还混有图片、音频

**Comment by jamebal** [comment]
<img width="435" alt="截屏2024-12-04 13 41 30" src="https://github.com/user-attachments/assets/0b358178-f96f-4d2a-81b0-ff0894acd0be">
请问每次都是卡在同步文件基本信息这吗？进度是完全不动还是动的很慢？如果是完全不动持续时间有多久？

**Comment by sansi98h** [comment]
> <img alt="截屏2024-12-04 13 41 30" width="435" src="https://private-user-images.githubusercontent.com/49510841/392240911-0b358178-f96f-4d2a-81b0-ff0894acd0be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzYzNDMsIm5iZiI6MTczMzM3NjA0MywicGF0aCI6Ii80OTUxMDg0MS8zOTIyNDA5MTEtMGIzNTgxNzgtZjk2Zi00ZDJhLTgxYjAtZmYwODk0YWNkMGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA1MjA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNjllYjllODVhMDA0NjQ5MDk0NGM0MTQ4NDg2ZTU5ODY1MTFmZWIzYmFlOGJhODZlNjliZjEzMWE2ODZlODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hnbnsw_4h1yq6D3xb_WBYzUWieHx9LegSSKzME8VBkk"> 请问每次都是卡在同步文件基本信息这吗？进度是完全不动还是动的很慢？如果是完全不动持续时间有多久？

不重启完全不动，重启一次卡住的值涨一点

**Comment by sansi98h** [comment]
跟新2.10.0后正常
