### ISSUE TITLE
请问大佬，后端可以支持直接使用windows的idea启动吗【不安装docker的那种】

### ISSUE THREAD

**Issue by H121** [jamebal/jmal-cloud-view#33]

**Comment by jamebal** [comment]
windowns目前还在测试

**Comment by H121** [comment]
> windowns目前还在测试

那请问前后端的技术栈以及版本可以说一下吗~我部署的时候老出错

**Comment by jamebal** [comment]
1. 安装MongoDB
2. clone 后端工程：
```shelll
git clone https://github.com/jamebal/jmal-cloud-server.git
```
3. 修改配置文件：
   - resources目录下的application-dev.yml，修改其MongoDB URI，一般默认就好
   - resources下的file.yml, 修改rootDir，改成自己本机的目录
4. 启动后端
5. clone 前端并启动工程：
```shell
 git clone https://github.com/jamebal/jmal-cloud-view.git
 cd jmal-cloud-view
 npm install
 npm run dev
```

**Comment by H121** [comment]
> 1. 安装MongoDB
> 2. clone 后端工程：
> 
> ```
> git clone https://github.com/jamebal/jmal-cloud-server.git
> ```
> 
> 3. 修改配置文件：
>    
>    * resources目录下的application-dev.yml，修改其MongoDB URI，一般默认就好
>    * resources下的file.yml, 修改rootDir，改成自己本机的目录
> 4. 启动后端
> 5. clone 前端并启动工程：
> 
> ```shell
>  git clone https://github.com/jamebal/jmal-cloud-view.git
>  cd jmal-cloud-view
>  npm install
>  npm run dev
> ```

前端的node版本以及npm版本呢~我前端run的时候报了一堆错~小菜鸡的挣扎

**Comment by jamebal** [comment]
node : v16.x.x

**Comment by H121** [comment]
> node : v16.x.x

好的好的，感谢佬！

**Comment by H121** [comment]
> node : v16.x.x

![image](https://user-images.githubusercontent.com/58348609/199634983-654d68ce-a2ba-4118-9648-4e653136e099.png)
尝试了之后还是一直报这种错误，我用的是node16.15.0版本。。。是我前端环境有什么问题吗还是

**Comment by jamebal** [comment]
先清下缓存，在npm install 试试

**Comment by H121** [comment]
> 先清下缓存，在npm install 试试

已解决，感谢大佬。
建议后来的小伙伴，如果是用了nvm去切版本记得操作是
npm cache clean --force
npm install
npm run dev
