### ISSUE TITLE
在Docker Desktop里部署双击无法打开office文档

### ISSUE THREAD

**Issue by PIPUSHIC** [jamebal/jmal-cloud-view#330]
在Docker Desktop里部署双击无法打开office文档
![2024-12-08_163842](https://github.com/user-attachments/assets/564c846a-32c9-4c4e-9b63-a26bd4ef3136)

**Comment by jamebal** [comment]
https://jmalcloud.github.io/guide/aq/office-502.html#_2-%E6%96%87%E6%A1%A3%E5%AE%89%E5%85%A8%E4%BB%A4%E7%89%8C%E7%9A%84%E6%A0%BC%E5%BC%8F%E4%B8%8D%E6%AD%A3%E7%A1%AE%E8%AF%B7%E4%B8%8E%E6%82%A8%E7%9A%84%E6%96%87%E6%A1%A3%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%AE%A1%E7%90%86%E5%91%98%E8%81%94%E7%B3%BB%E3%80%82

**Comment by PIPUSHIC** [comment]
可以打开了，非常感谢！！
