### ISSUE TITLE
新增角色bug

### ISSUE THREAD

**Issue by H121** [jamebal/jmal-cloud-view#34]
有两个bug如下：
1、在新加了用户之后，发现用户登录会出现404
![Uploading 微信图片_20221103200645.png…]()

![image](https://user-images.githubusercontent.com/58348609/199715258-7cfc4428-f168-4e35-9b82-5c4c39e88f07.png)
2、并且用户被删除后再次创建会出现用户已存在的bug
![image](https://user-images.githubusercontent.com/58348609/199716062-d110fa9d-9442-4194-b1a3-de2e73b8f6a7.png)

**Comment by H121** [comment]
![image](https://user-images.githubusercontent.com/58348609/199716660-d37103c5-8855-4b26-bf16-c98bf22ae63e.png)
补充：登录的用户为224这个号。
然后我新建了225，又删除了。过了一小会再次创建发现还是不行【偶然发现】

**Comment by H121** [comment]
另外请问大佬，是否可以实现按网盘【我想分成组织以及个人两部分】分配容量。个人按固定份额去分配，组织容量由管理员分配

**Comment by H121** [comment]
![image](https://user-images.githubusercontent.com/58348609/199725531-359f70f0-7a1c-47b8-983e-9d09e78021e4.png)
发现新增目录后也会跳转不过去
问题有些多，盼望得到大佬的回复~

**Comment by H121** [comment]
![image](https://user-images.githubusercontent.com/58348609/199769859-4e264190-98cc-49a5-94c2-4f8bb00ac38b.png)
![image](https://user-images.githubusercontent.com/58348609/199769956-6f2c769d-1b54-452a-84f1-c069650a8d2e.png)
![image](https://user-images.githubusercontent.com/58348609/199770093-1f47e563-a9dd-4809-9592-b7817db3dfbb.png)
从压缩包里面解压命名会乱码，bug

**Comment by jamebal** [comment]
> ![image](https://user-images.githubusercontent.com/58348609/199725531-359f70f0-7a1c-47b8-983e-9d09e78021e4.png) 发现新增目录后也会跳转不过去 问题有些多，盼望得到大佬的回复~

这里是菜单，并不是目录

**Comment by jamebal** [comment]
> 另外请问大佬，是否可以实现按网盘【我想分成组织以及个人两部分】分配容量。个人按固定份额去分配，组织容量由管理员分配
可以分成两个用户

**Comment by H121** [comment]
> > ![image](https://user-images.githubusercontent.com/58348609/199725531-359f70f0-7a1c-47b8-983e-9d09e78021e4.png) 发现新增目录后也会跳转不过去 问题有些多，盼望得到大佬的回复~
> 
> 这里是菜单，并不是目录

那是不是前端设置了一个菜单，后端就得去增加一次controller的映射

**Comment by jamebal** [comment]
> > > 另外请问大佬，是否可以实现按网盘【我想分成组织以及个人两部分】分配容量。个人按固定份额去分配，组织容量由管理员分配
> > 
> > 
> > 可以分成两个用户
> 
> 组织里面应该是多个人共享这里面的内容。分成两个用户的话，其他成员如何有这个用户的增删改查权限呢以及在其他成员界面如菜单这样显示

目前不能按组织划分，只能按单个用户来使用

**Comment by jamebal** [comment]
> > > ![image](https://user-images.githubusercontent.com/58348609/199725531-359f70f0-7a1c-47b8-983e-9d09e78021e4.png) 发现新增目录后也会跳转不过去 问题有些多，盼望得到大佬的回复~
> > 
> > 
> > 这里是菜单，并不是目录
> 
> 那是不是前端设置了一个菜单，后端就得去增加一次controller的映射

需要前端需要添加相应的界面

**Comment by jamebal** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/58348609/199725531-359f70f0-7a1c-47b8-983e-9d09e78021e4.png) 发现新增目录后也会跳转不过去 问题有些多，盼望得到大佬的回复~
> > > > 
> > > > 
> > > > 这里是菜单，并不是目录
> > > 
> > > 
> > > 那是不是前端设置了一个菜单，后端就得去增加一次controller的映射
> > 
> > 
> > 需要前端需要添加相应的界面
> 
> 无法实现动态添加吗大佬

你想要什么样的效果

**Comment by H121** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/58348609/199725531-359f70f0-7a1c-47b8-983e-9d09e78021e4.png) 发现新增目录后也会跳转不过去 问题有些多，盼望得到大佬的回复~
> > > > > 
> > > > > 
> > > > > 这里是菜单，并不是目录
> > > > 
> > > > 
> > > > 那是不是前端设置了一个菜单，后端就得去增加一次controller的映射
> > > 
> > > 
> > > 需要前端需要添加相应的界面
> > 
> > 
> > 无法实现动态添加吗大佬
> 
> 你想要什么样的效果

动态添加一个菜单，然后根据权限去访问

**Comment by H121** [comment]
> > > > > > > ![image](https://user-images.githubusercontent.com/58348609/199725531-359f70f0-7a1c-47b8-983e-9d09e78021e4.png) 发现新增目录后也会跳转不过去 问题有些多，盼望得到大佬的回复~
> > > > > > 
> > > > > > 
> > > > > > 这里是菜单，并不是目录
> > > > > 
> > > > > 
> > > > > 那是不是前端设置了一个菜单，后端就得去增加一次controller的映射
> > > > 
> > > > 
> > > > 需要前端需要添加相应的界面
> > > 
> > > 
> > > 无法实现动态添加吗大佬
> > 
> > 
> > 你想要什么样的效果
> 
> 动态添加一个菜单，然后根据权限去使用

**Comment by jamebal** [comment]
动态添加一个目录吧

**Comment by H121** [comment]
> 动态添加一个目录吧

是的，类似这个功能。只有特定的人可以访问这个目录的话，这种如何去实现呢

**Comment by jamebal** [comment]
动态添加一个目录，然后根据角色去控制该目录的读写权限

**Comment by jamebal** [comment]
这个功能不错

**Comment by H121** [comment]
> 动态添加一个目录，然后根据角色去控制该目录的读写权限

![image](https://user-images.githubusercontent.com/58348609/199865994-d00f07fd-b433-4a9e-8ec1-33648303993c.png)
权限 只能对菜单进行修改，所以动态添加目录是指在菜单管理这边添加吗
![image](https://user-images.githubusercontent.com/58348609/199866085-fbfe76c1-e723-4fad-bf89-356529feba27.png)

**Comment by H121** [comment]
> 这个功能不错

其实这个功能就是实现了组织分配。所以才有这个问题
