### ISSUE TITLE
在手机浏览器上打开分享链接 会不停的自动刷新界面

### ISSUE THREAD

**Issue by HeiHeiHeMianMa** [jamebal/jmal-cloud-view#345]
在手机浏览器上打开分享链接 会不停的自动刷新界面，必现，甚至在pc端微信中打开也可以复现

**Comment by HeiHeiHeMianMa** [comment]
顺便吐槽一下，为什么这个项目做的很好，却一直不火呢

**Comment by jamebal** [comment]
更新下镜像试试

**Comment by HeiHeiHeMianMa** [comment]
> 更新镜像

是在demo发现的，直接用手机浏览器打开这个链接就可以发现，https://demo2.jmalx.com:42999/s/FMO8aKto

**Comment by jamebal** [comment]
demo镜像没更新😂

**Comment by jamebal** [comment]
demo更新了

**Comment by HeiHeiHeMianMa** [comment]
> 演示更新

好了，感谢！
