### ISSUE TITLE
预览doc等Office文档提示未知错误

### ISSUE THREAD

**Issue by userAmani** [jamebal/jmal-cloud-view#37]
![image](https://user-images.githubusercontent.com/29222146/205576965-835e4171-e03e-43db-87c9-aa9a076b8fa7.png)

**Comment by userAmani** [comment]
> 修改nginx配置文件即可：
> 
> ```shell
> map $http_upgrade $connection_upgrade {
>     default upgrade;
>     ''      close;
> }
> map $http_host $this_host {
>     "" $host;
>     default $http_host;
> }
> map $http_x_forwarded_proto $the_scheme {
>      default $http_x_forwarded_proto;
>      "" $scheme;
> }
> map $http_x_forwarded_host $the_host {
>     default $http_x_forwarded_host;
>     "" $this_host;
> }
> 
> server
> {
>     listen 80;
>     server_name cloud1.jmal.top;
>     rewrite ^(.*) https://cloud1.jmal.top$1 permanent;
> }
> 
> server {
>     listen 443 ssl;
>     server_name    cloud1.jmal.top;
>         
>     ssl_certificate      /www/server/panel/vhost/cert/cloud1.jmal.top/fullchain.pem;
>     ssl_certificate_key  /www/server/panel/vhost/cert/cloud1.jmal.top/privkey.pem;
> 
>     ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4; 
>     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>     
>         location / {
>                 proxy_pass   http://localhost:12070/;
>                 proxy_redirect http:// $scheme://;
>                 proxy_http_version 1.1;
>                 proxy_set_header X-real-ip $remote_addr;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Real-PORT $remote_port;
>                 proxy_set_header X-Forwarded-Proto $the_scheme;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header Host $http_host;
>                 proxy_set_header Scheme $scheme;
>                 proxy_set_header Server-Protocol $server_protocol;
>                 proxy_set_header Server-Name $server_name;
>                 proxy_set_header Server-Addr $server_addr;
>                 proxy_set_header Server-Port $server_port;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection $connection_upgrade;
> 
>         }
>          location /file/ {
>                 proxy_pass  http://localhost:12070/file/;
>                 proxy_redirect http:// $scheme://;
>                 proxy_http_version 1.1;
>                 proxy_set_header X-real-ip $remote_addr;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Real-PORT $remote_port;
>                 proxy_set_header X-Forwarded-Host $the_host/file;
>                 proxy_set_header X-Forwarded-Proto $the_scheme;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header Host $http_host;
>                 proxy_set_header Scheme $scheme;
>                 proxy_set_header Server-Protocol $server_protocol;
>                 proxy_set_header Server-Name $server_name;
>                 proxy_set_header Server-Addr $server_addr;
>                 proxy_set_header Server-Port $server_port;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection $connection_upgrade;
>          }
>     
> }
> ```

好的谢谢，我本地开发环境运行前端和后端功能都正常，但是文档预览不了，Office预览的服务我也可以使用吗，我用docker起的office服务发现使用不了，可以解答下吗

**Comment by jamebal** [comment]
你不是用jc.sh脚本部署的吗

**Comment by userAmani** [comment]
> 你不是用jc.sh脚本部署的吗

是在本地编译部署的，nginx配置了dcocker里的office服务但是Office预览有些问题，不知道什么解决了。

**Comment by jamebal** [comment]
https://blog.jmal.top/s/deploy-jmalcloud
你看看这个，启动office服务后需要在nginx里面配置一下

**Comment by userAmani** [comment]
> https://blog.jmal.top/s/deploy-jmalcloud 你看看这个，启动office服务后需要在nginx里面配置一下

好的谢谢大佬
