### ISSUE TITLE
密码重置后初始密码是多少？

### ISSUE THREAD

**Issue by Luoluo-001** [jamebal/jmal-cloud-view#38]
重置过程也没有密码提示，也不知道重置为多少了

**Comment by Luoluo-001** [comment]
新版本的镜像启动不起来，报错是mongo那边的，不知道是不是有大的改动


?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jamebal/jmal-cloud-view"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月6日(星期二) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jamebal/jmal-cloud-view] 密码重置后初始密码是多少？ (Issue #38)





 
初始密码为: jmalcloud

**Comment by jamebal** [comment]
如果是v2.2.40之前的版本需要升级
https://blog.jmal.top/s/docker-jmalcloud
