### ISSUE TITLE
打开word的时候报DocsAPI is not defined，请问引用的是哪个包

### ISSUE THREAD

**Issue by sjgfa** [jamebal/jmal-cloud-view#39]
![image](https://user-images.githubusercontent.com/53327141/211269026-3427db0a-43b3-4242-924a-2ca2ab958001.png)

**Comment by jamebal** [comment]
这个需要用到onlyoffice, 参考[这里](https://blog.jmal.top/s/%E9%83%A8%E7%BD%B2jmalcloud#3---%E9%9D%9E%E5%BF%85%E9%A1%BB-%E5%90%AF%E5%8A%A8onlyoffice-%E6%96%87%E6%A1%A3%E9%A2%84%E8%A7%88-%E5%92%8C-drawio-%E6%B5%81%E7%A8%8B%E5%9B%BE%E7%BC%96%E8%BE%91-)
