### ISSUE TITLE
按照web端的readme搭好之后，访问显示服务器出错

### ISSUE THREAD

**Issue by huaze28** [jamebal/jmal-cloud-view#4]
按照web端的readme搭好之后，访问显示服务器出错，服务器端需要搭建吗，怎么搭建？

**Comment by jamebal** [comment]
具体是什么错误呢？
也可以使用docker部署,更加方便: https://blog.jmal.top/s/docker-jmalcloud

**Comment by huaze28** [comment]
> 具体是什么错误呢？
> 也可以使用docker部署,更加方便: https://blog.jmal.top/s/docker-jmalcloud

用这个教程安装还需要按readme那里那样安装吗

**Comment by huaze28** [comment]
> 具体是什么错误呢？
> 也可以使用docker部署,更加方便: https://blog.jmal.top/s/docker-jmalcloud

搭好了，谢谢
