### ISSUE TITLE
按照dev部署方式后，如何将后台的localhost更换为服务器ip？

### ISSUE THREAD

**Issue by fengduanqiao** [jamebal/jmal-cloud-view#42]
如题，多谢~

**Comment by jamebal** [comment]
在`src -> main -> cloudisk -> ClouddiskApplication`下
启动main方法即可

**Comment by jamebal** [comment]
如果是在前端改后台的ip地址，在`vue.config.js`里面，将`target: 'http://localhost:8088',`改成：`target: 'http://服务器ip:8088',`

**Comment by fengduanqiao** [comment]
> 



> 如果是在前端改后台的ip地址，在`vue.config.js`里面，将`target: 'http://localhost:8088',`改成：`target: 'http://服务器ip:8088',`

![image](https://user-images.githubusercontent.com/5849592/236770462-5aa47d2d-e06c-4b38-8b3d-946af47d6326.png)
http://localhost:9528/sockjs-node/info?t=1683532932400，前端访问后端出现了上述网站，即使完成了vue.config.js里面的将localhost替换为服务器ip，还是同样的问题！

**Comment by jamebal** [comment]
前端和后端不在一台机器上吗

**Comment by fengduanqiao** [comment]
> host替换为服务器ip，还是同样的问题！

都部署在一台服务器上！

**Comment by fengduanqiao** [comment]
> `sockjs-node/info`是node实现热更新功能的端点，跟后端没有关系，具体提示什么呢

![image](https://user-images.githubusercontent.com/5849592/236775041-f282ca69-6c05-4b05-96ae-b41755ac21d8.png)
就是前端访问请求后端数据的时候，这边访问的是localhost，这个localhost访问的是window，而不是服务器！

**Comment by jamebal** [comment]
1.`http://localhost:9528/sockjs-node/info`这是前端的热更新功能跟后端没关系，下面那个成功的返回的是什么
2.`http://localhost:9528/api/**`,这种请求就是经过代理访问了后端服务器

**Comment by fengduanqiao** [comment]
> 

![image](https://user-images.githubusercontent.com/5849592/236777233-0f30f7f0-e121-480d-b4a7-bd82fafff3c2.png)
如果把http://localhost:9528/sockjs-node/info?t=1683532942964，换成http://服务器ip:9528/sockjs-node/info?t=1683532942964，就出现上面的截图所示！

**Comment by jamebal** [comment]
那就使用http://服务器ip:9528

**Comment by fengduanqiao** [comment]
> 在`vue.config.js`里面，

修改了在vue.config.js里面，把localhost换成服务器ip，重新运行后，前端一点击创建，还是访问的localhost！而不是服务器ip的服务端

**Comment by jamebal** [comment]
浏览器网络工具里看起是`http://localhost:9528/api/**`这个样的，由于配置了代理，实际上访问的是`http://服务器ip:8088/**`

**Comment by fengduanqiao** [comment]
> 上访问的是

/api网址访问的确实的服务器ip，但创建管理员一直不成功！

**Comment by jamebal** [comment]
> > 上访问的是
> 
> /api网址访问的确实的服务器ip，但创建管理员一直不成功！

提示什么

**Comment by fengduanqiao** [comment]
> > > 上访问的是
> > 
> > 
> > /api网址访问的确实的服务器ip，但创建管理员一直不成功！
> 
> 提示什么

每次点击创建，就报错：
![image](https://user-images.githubusercontent.com/5849592/236809686-ffbf9937-7fef-44cf-b66a-8ef62e5d46ba.png)

**Comment by jamebal** [comment]
后端有报错吗

**Comment by IsEzuxoay** [comment]
请问，数据库文件在哪里啊？实在是没找到。。
