### ISSUE TITLE
希望增加软链接的支持

### ISSUE THREAD

**Issue by HoGC** [jamebal/jmal-cloud-view#50]
有个文件夹想共享给某个用户，尝试使用软链接的方式，但是实际测试下来无法使用

**Comment by jamebal** [comment]
是怎么样无法使用？比如这是测试环境的utils目录: https://cloud1.zhujunhao.xyz/s?s=64a92e8858e2a371520427a5

**Comment by HoGC** [comment]
你看下我的操作有没有问题
![image](https://github.com/jamebal/jmal-cloud-view/assets/50402699/b820062e-c58f-47f2-a357-7b80c8e51f3a)
![image](https://github.com/jamebal/jmal-cloud-view/assets/50402699/f6d0e417-9a92-476c-ac70-7528e30eb063)

**Comment by jamebal** [comment]
操作没问题，我试了一下，确实不支持软链接

**Comment by HoGC** [comment]
有计划支持是吗，增加软链接主要还是为了不同用户可以共享一个文件夹，或者你能在前端里增加这种组内共享操作那就更好了

**Comment by jamebal** [comment]
嗯，直接在前端加

**Comment by HoGC** [comment]
如何使用挂载文件夹的功能

**Comment by jamebal** [comment]
在分享的链接里登陆其他账号即可挂载
<img width="682" alt="截屏2023-08-15 23 08 43" src="https://github.com/jamebal/jmal-cloud-view/assets/49510841/48d9ad7e-7b60-46a7-be1b-3134dd8c65a3">
