### ISSUE TITLE
如何将该网盘挂载到本地呢？

### ISSUE THREAD

**Issue by xcngl** [jamebal/jmal-cloud-view#52]
如何将该网盘挂载到本地呢？现在支持该功能吗？
      像windows添加网络位置、Macos连接服务器那样。

**Comment by jamebal** [comment]
可以使用WebDAV挂载

**Comment by xcngl** [comment]
> 可以使用WebDAV挂载

<img width="924" alt="image" src="https://github.com/jamebal/jmal-cloud-view/assets/110588072/da0159cb-a752-4d52-a187-62dbd39b721a">
貌似看不到之前创建的文件夹和文件

**Comment by xcngl** [comment]
文件夹改成中文或英文能看到了
