### ISSUE TITLE
过期的分享文件仍然可以被下载

### ISSUE THREAD

**Issue by HoGC** [jamebal/jmal-cloud-view#62]
本来分享的链接中文件点击下载后使用以下链接下载
http://{host}/api/public/s/preview/{filename}?fileId={fileId}&shareId={shareId}&shareToken=none
然后发现在文件右键复制下载链接能得到个
http://{host}/api/file/{username}/{path}/{filename}

这样的话使用不带参数的下载链接可以无视分享到期时间

这是我使用的你demo分享的一个文件，一已经过期了，但是还是能被下载
https://demo.zhujunhao.top/api/file/demo/%E6%9C%AA%E5%91%BD%E5%90%8D%E6%96%87%E4%BB%B6.pptx.zip

**Comment by jamebal** [comment]
演示环境中分享过期的文件仍然能下载，应该是CDN的缓存：
```shell
cache-control: max-age=10800
x-cache: HIT
```

**Comment by HoGC** [comment]
之前分享的文件被别人取消了，
我测试的时候分享过期了还能用http:{host}/api/file/{username}/{path}/{filename}访问
一旦我取消那个过期的分享，url就立即不能访问了，这是缓存问题吗

**Comment by jamebal** [comment]
文件取消分享或者分享过期都是一样的，你可以使用`curl -D - -o example.txt http://example.com/file.txt
`试试，看看是否有缓存

**Comment by HoGC** [comment]
好像确实是缓存带来的问题
