### ISSUE TITLE
是否可以给文件添加标签系统，便于素材管理检索

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-view#63]
是否可以给文件添加标签系统，便于素材管理检索，比如视频素材，会有很多的属性，城市、实拍、特效、等等标签。标签系统可以方便检索素材

**Comment by kokojacket** [comment]
@jamebal demo网址失效了

**Comment by kokojacket** [comment]
太强了！！！！

**Comment by kokojacket** [comment]
更新后不记得密码进不去了

**Comment by jamebal** [comment]
看这里[重置密码](https://github.com/jamebal/jmal-cloud-view?tab=readme-ov-file#%E9%87%8D%E5%90%AF%E7%AE%A1%E7%90%86%E5%91%98%E5%AF%86%E7%A0%81)

**Comment by kokojacket** [comment]
重置后，只是重置了密码，没有充值用户名是吧

**Comment by jamebal** [comment]
是的

**Comment by kokojacket** [comment]
已经体验过啦~~。目前的标签系统，似乎不能直接在搜索框，基于标签进行搜索

**Comment by jamebal** [comment]
后续版本加全文搜索

**Comment by kokojacket** [comment]
> 后续版本加全文搜索

太感谢了，加油！！！
