### ISSUE TITLE
运行./js.sh install 拉取office组件时总是卡住下载不动

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#65]
如下图，拉取office组件时卡住不动，系统版本是Centos 7.7，已重装多次系统还是无法正常下载office组件，请问是什么原因，如何解决
<img width="740" alt="PixPin_2024-03-02_00-30-24" src="https://github.com/jamebal/jmal-cloud-view/assets/106538519/7883361a-2b00-4465-a15c-35fb12757add">

**Comment by jamebal** [comment]
如果实在拉不下来,可以修改docker-compose.yml文件 将其中的`registry.cn-guangzhou.aliyuncs.com/jmalcloud/onlyoffice_documentserver`改为 `onlyoffice/documentserver`再试试
