### ISSUE TITLE
JmalCloud问题及优化建议，内容较多，请您耐心阅读

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#66]
关于使用JmalCloud的建议及优化，首先我非常喜欢JmalCloud，从一键式部署方便安装到体验功能强大的office编辑和文件预览再到UI设计等等多方面，是我用过最舒服的私人云盘，毫无疑问我已经成功被JmalCloud圈粉，但经过我使用后发现一些不足的地方，希望您能够优化JmalCloud让它变得更好，以下是我的建议，篇幅较长，请您耐心阅读，最后希望您能够采纳我的建议。

一：权限问题
1.如下图所示：在角色管理中分配权限时发现，如果不勾选查询用户，那么对应角色的账号便无法登录，出现没有权限报错，希望能够优化角色权限逻辑，使其更能直观的表示对应的功能。
![image-20240302211835543](https://github.com/jamebal/jmal-cloud-view/assets/106538519/f009aea0-d7db-43c8-a37d-5b21fafea983)
2.在用户管理中，修改用户时，无法自定义重置账号后的密码
![image-20240302220440618](https://github.com/jamebal/jmal-cloud-view/assets/106538519/a68ad6cf-347b-44fa-a2d7-3a2b6b68d2f7)

二：上传文件问题
1.使用上传功能时，如下图所示 ，上传后会丢失文件，这种现象经常出现，有时会出现一个文件都上传不上去，但是却提示文件上传成功，无论我如何刷新页面也不会出现。
![PixPin_2024-03-02_21-42-34](https://github.com/jamebal/jmal-cloud-view/assets/106538519/2379422d-95da-47cc-8535-4542c254b23b)
2.上传/删除-文件或者文件夹后，页面不会立即显示需要手动刷新才能显示，希望能够上传或删除后能刷新下页面。

3.上传进度条显示问题，当我上传文件夹中的视频时如图所示：进度条会卡死，并且会有文件丢失，如果正常显示时，我刷新页面，进度条也会卡死。
![PixPin_2024-03-02_21-54-19](https://github.com/jamebal/jmal-cloud-view/assets/106538519/a11765bd-335b-4b8d-b422-4a5ce80d018c)
4.没有主动交互的下载传输按钮，只有上传或下载时才被动出现进度条，无法看到传输记录。

三：下载速度问题
 我使用的服务器是centos 7.7版本，上传带宽是35MB/s，下行带宽是150MB/s，当我下载文件夹时网速明显比下载单个文件慢（慢很多很多），而且下载稳定在1000多kb上，我本地网络下行带宽给能跑到30MB/s，按照我本地的带宽来讲下载速度不应该这么慢，我使用sppedtest-cli对本地网络和服务器网络进行了测速，发现没有问题，测速及下载过程如下图所示：对于私人云盘来说，下载速度尤为重要，请您分析。
<img width="1186" alt="PixPin_2024-03-02_22-37-33" src="https://github.com/jamebal/jmal-cloud-view/assets/106538519/1af79415-349a-4477-aad6-72ee61170fbd">
![PixPin_2024-03-02_22-43-27](https://github.com/jamebal/jmal-cloud-view/assets/106538519/99c38027-6c77-4178-8a6b-494e94427287)
四：当文件上传失败或者其他报错信息弹出时能否说明原因，方便反馈

**Comment by jamebal** [comment]
感谢您的反馈, 后续将会修复上述问题

**Comment by Xiaoph123** [comment]
感谢您的耐心阅读，希望JmalCloud越来越好

**Comment by jamebal** [comment]
请问上传夹丢失文件的问题应该如何重现

**Comment by pbmht** [comment]
上传文件夹，本地文件夹有多个文件，有多个文件500M左右，就会出现上传后丢失文件现象！上传的提示列表不能关闭，提示还有文件正在上传！

**Comment by Xiaoph123** [comment]
丢文件问题
1.如果文件夹数量少，且最后的子文件内文件少，是有很大概率能上传成功，但偶尔会有丢失
2.如果文件夹嵌套很多子文件夹，并且无论子文件内文件数量多少那么只会生成嵌套的文件夹，在最后子文件内的文件大概率全部丢失，有小概率会上传成功
3.如果只有父文件夹且父文件夹下有很多文件是同类型或不同类型的文件，那么大概率会丢失文件，测试发现上传多次均会有文件丢失

**Comment by jamebal** [comment]
> 丢文件问题 1.如果文件夹数量少，且最后的子文件内文件少，是有很大概率能上传成功，但偶尔会有丢失 2.如果文件夹嵌套很多子文件夹，并且无论子文件内文件数量多少那么只会生成嵌套的文件夹，在最后子文件内的文件大概率全部丢失，有小概率会上传成功 3.如果只有父文件夹且父文件夹下有很多文件是同类型或不同类型的文件，那么大概率会丢失文件，测试发现上传多次均会有文件丢失

请问您使用的是什么浏览器, 如果可以话能否提够大概率会丢失文件的文件夹, 可上传至演示站点:jmal.cc/demo

**Comment by Xiaoph123** [comment]
你有没有别的联系方式邮箱也行，我打包发给你，我上传频繁被拦截了
![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/3550b8ea-c6c8-4b1a-a61b-c28573964c05)

**Comment by jamebal** [comment]
> 你有没有别的联系方式邮箱也行，我打包发给你，我上传频繁被拦截了 ![image](https://private-user-images.githubusercontent.com/106538519/313383890-3550b8ea-c6c8-4b1a-a61b-c28573964c05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzI4NjcsIm5iZiI6MTcxMDU3MjU2NywicGF0aCI6Ii8xMDY1Mzg1MTkvMzEzMzgzODkwLTM1NTBiOGVhLWM2YzgtNGIxYS1hNjFiLWMyODU3Mzk2NGMwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwNzAyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODE2YWU3Y2QzN2NhZWRlYjg4NDk3MGMxOTMyZWNmNzliZGE5OGNjM2NlZGM3YTUwNGZmY2I3NTM0NjFkM2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0fK6EToWEqELVLsa-6NZSJ6ZeV-IYQpThHVVr9PpX8Q)

现在解除限制了

**Comment by Xiaoph123** [comment]
在‘丢失文件测试’文件夹中我上传了3个demo，第一个demo中最后的两个子文件夹内的exe文件出现丢失，第二个demo中Release目录下有82个文件（一个文件夹和81个单文件）上传后只有79个文件，第三个demo中，最后子目录下文件丢失（上传状态看不到任何信息，我默认为丢失，可能在上传中只是我看不到状态）

**Comment by jamebal** [comment]
好的,感谢反馈

**Comment by pbmht** [comment]
用360浏览器和谷歌浏览器都会出现丢失文件情况，而且没有规律，上传文件夹丢失文件很容易出现的，辛苦版主查找原因！

**Comment by pbmht** [comment]
新版本解决丢失文件问题了吗？

**Comment by Xiaoph123** [comment]
> 新版本解决丢失文件问题了吗？

还未测试，等我下午测试下

**Comment by 0917python** [comment]
jmalcloud如何设置公共文件夹，让所有用户都可以直接访问,并且给图片打的标签可以所有用户共享？

**Comment by jamebal** [comment]
> jmalcloud如何设置公共文件夹，让所有用户都可以直接访问,并且给图片打的标签可以所有用户共享？

目前没有这个功能
