### ISSUE TITLE
JmalCloud使用反馈

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#67]
继续反馈使用JmalCloud过程中的问题
一：问题
   1.office组件问题
     打开office文件有时会提示“无法预览需要下载”只有我退出账号，重新登录后才能正常预览。
   2.复制和移动问题
      移动文件或复制文件有时无法移动到或复制到指定目录，尤其是office文件（移动或复制后目录显示为空）。
  3.在线预览大文件视频时会卡顿不流畅（网络良好状态下）。

二：功能需求
   1.在共享模块下希望增加用户和组的功能使用目的是家庭共享（因为有时家人或朋友记不住链接，不如直接在自己账号中登录JamlCloud查看方便）。

对于频繁的指出JamlCloud中存在的问题并不是觉得JamlCloud不好，恰恰是因为很喜欢，所以想要JamlCloud变得更好！！！
最后弱弱的问一句，作者何时会更新JmalCloud（期待满满）。

**Comment by jamebal** [comment]
1.office组件问题:
当前版本遇到类似问题可以通过刷新界面解决, 其他各种问题也可通过刷新界面解决(后续会优化这个问题)
3.在线预览大文件视频时会卡顿不流畅
这个取决于服务器的上传带宽和视频码率(后续可转码为低码率视频提供在线预览)

共享模块: 
目前在共享链接里登陆朋友自己的账号, 可以将文件夹挂载到他自己的网盘中

**Comment by jackloves111** [comment]
反馈：还没用上，但是看demo效果，真的不错！！！感谢

**Comment by jamebal** [comment]
> 共享模块：将文件夹挂载到他自己的网盘中后，无法预览视频，图片和文档呢

v2.7.1已修复该问题
