### ISSUE TITLE
打开office文档出现错误

### ISSUE THREAD

**Issue by pbmht** [jamebal/jmal-cloud-view#74]
win10系统 Docker Desktop 虚拟机
使用docker compose up -d 部署环境
在预览上传文件 word,excel文件时会出现下载失败提示：

https://github.com/pbmht/jpg/blob/33c84ed69d350bef81895de1e18c46fa132b85e2/111.jpg

是部署的哪有问题吗？

**Comment by jamebal** [comment]
刷新整个界面试试

**Comment by pbmht** [comment]
刷新整个界面没有效果，还是报错！
docker-compose.yml文件是 例子原文件，没做任何修改，知道为什么就报错！

version: "3"
services:
  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: mongodb://mongo:27017/jmalcloud
      TZ: Asia/Shanghai
    volumes:
      - ./docker/jmalcloud/files:/jmalcloud/files/
    restart: unless-stopped
  mongo:
    container_name: jmalcloud_mongodb
    image: mongo:4.4
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.5
  nginx:
    container_name: jmalcloud_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: Asia/Shanghai
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: unless-stopped
  office: # Optional
    container_name: jmalcloud_office
    image: onlyoffice/documentserver:7.0.0.132
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
  drawio-webapp: # Optional
    container_name: jmalcloud_drawio
    image: jgraph/drawio:20.2.3
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped

**Comment by jamebal** [comment]
感谢反馈; 我在windows里试试

**Comment by pbmht** [comment]
> 感谢反馈; 我在windows里试试

发现使用本地环境测试地址访问就会出现错误，localhost:7070 或 127.0.0.1:7070 访问都会出错！但使用固定IP地址做服务器就能正常访问！辛苦版主测试一下！

**Comment by 593769290** [comment]
这应该是要加个配置项？可以灵活设定onlyofiice的访问路径？如果没有这个配置项，你使用127.0.0.1:7070去访问网盘，然后他想去127.0.0.1:xxxx 去找onlyoffice插件肯定找不到了。应该不算是应用bug，是配置类问题吧。或者 明确说明不能使用127.0.0.1:7070去访问网盘。  @jamebal

**Comment by jamebal** [comment]
v2.8.1已修复该问题
