### ISSUE TITLE
我看主容器自带8088端口，为什么还要带nginx？

### ISSUE THREAD

**Issue by jxjxjhjh** [jamebal/jmal-cloud-view#75]
我自己有别的nginx容器作为整个vps的反代服务，能否省略jmalcloud docker中的nginx呢？把jmalcloud的8088容器暴露出来，直接反代不行吗？

**Comment by jamebal** [comment]
理论上可以,但是安装和升级非常的麻烦

**Comment by jamebal** [comment]
8088端口是服务端, nginx是前端界面
