### ISSUE TITLE
写文章点击后，报错404了？

### ISSUE THREAD

**Issue by 593769290** [jamebal/jmal-cloud-view#79]
当前版本：v2.7.1 
![写文章](https://github.com/jamebal/jmal-cloud-view/assets/17897483/dcce7300-5111-4cef-99b9-beddb65ee6a9)

在文件页面空白处，右键 写文章，会打开一个404的报错页面      http://192.168.1.219:7080/404?operation=new  [本网盘页面地址为http://192.168.1.219:7080 ]
是哪里的设定不对吗？

**Comment by jamebal** [comment]
打开浏览器控制台看看有什么错误信息:
  在 Chrome 中，可以按下 Ctrl + Shift + J（Windows / Linux）或 Cmd + Option + J（Mac）。
  在 Firefox 中，可以按下 Ctrl + Shift + K（Windows / Linux）或 Cmd + Option + K（Mac）。
  在 Safari 中，需要先启用开发菜单（在偏好设置中勾选“显示开发菜单”），然后选择“开发” > “显示 JavaScript 控制台”。

开启控制台后点击写文章,看看有什么错误信息

**Comment by 593769290** [comment]
神奇了，现在又可以打开这个写文章页面了，同时网站blog端口页面也可以打开了。之前网站blog页面也不能打开。
