### ISSUE TITLE
建议分配权限中增加挂载到我的云盘操作权限

### ISSUE THREAD

**Issue by pbmht** [jamebal/jmal-cloud-view#82]
目前挂载的文件夹只能上传，不能新建，编辑，删除等操作！建议挂载到我的云盘文件夹新建，删除，编辑等权限在角色分配权限中可以设置，方便用户对挂载的文件夹的操作！谢谢！

**Comment by v5star** [comment]
我也遇到这个问题，使用分享的链接打开，协同编辑是可以的，挂载后就不行了，提示链接已失效。目前这个问题，大佬们有好的解决办法吗？
![5](https://github.com/jamebal/jmal-cloud-view/assets/31580191/fda29ca0-695d-4e7a-b176-a57f0f399271)
![6](https://github.com/jamebal/jmal-cloud-view/assets/31580191/e606ac45-bab0-4219-bf80-3c9f2064ae30)
@jamebal
