### ISSUE TITLE
两点非常有竞争力的功能完善建议

### ISSUE THREAD

**Issue by death4444** [jamebal/jmal-cloud-view#85]
首先，非常感谢大佬的辛勤付出，才让我们有了这么好用的网盘工具；我个人看了一圈，什么nextcloud，seafile等等，虽然各有特色，但最轻量，功能恰到好处，集成blog，部署简单的，唯此一家！！有种终于等到你的感觉。
我从使用场景上提两个小小的需求，希望大佬有空余时间的时候，能考虑下实现。

1.上传功能，增加基于服务端的本地路径扫描
场景：在部署之前，服务器上已经存在大量文件，部署之后再逐个上传很麻烦，并且新上传的文件meta数据丢失，重复占用磁盘空间。
实现建议：通过设置服务端的路径，将路径下的文件递归扫一遍，并将支持的文件按原目录结构，托管到系统中。最好是仅生成DB数据，不要动原始file，这样侵入性最小。docker环境通过变量映射服务器端的本地目录。
补充需求：
文件按原目录结构托管
保留文件meta数据（非必须）
自动排除不支持的文件类型
扫描任务状态监控
异常文件反馈（不需要通知这么麻烦），最后形成一个清单即可

2.全文搜索，基于文档类型文件内容的全文检索
场景：对于文档比较多、文件命名不规范、且没有分类归档的情况，从模糊搜索，慢慢精确定位自己想要的文件，会方便很多。
对于我个人来说是个刚需，我现在是通过paperless-ngx以及AnyTXT Searcher曲线救国实现的。jmal-cloud实现了就可以all in one了
实现建议：类似C/S软件AnyTXT Searcher，网盘类的nextcloud-elasticsearch插件
补充需求：
能加上OCR对图片文本内容进行识别当然最好啦！（贪心）Umi-OCR项目的引擎就挺好的

**Comment by jamebal** [comment]
这两个功能非常不错

**Comment by death4444** [comment]
> 这两个功能非常不错

WOW，期待的搓着小手手~

**Comment by jamebal** [comment]
**1. 本地路径扫描**: 需要在docker-compose.yml文件中添加挂载路径
   例如: 
   我想添加系统文件夹`/home/test/doc`挂载到网盘, 用户名为`admin`下的文件夹中(必须挂载到某个用户下,否则扫描不到)
   需要在volumes加上
  ```yml
volumes:
      - xxxx:/jmalcloud/files
      - /home/test/doc:/jmalcloud/files/admin/doc
```
   使用`docker-cmpose up -d`重启后, 在网盘设置中点击重建索引, 该操作会扫描整个`/jmalcloud/files`目录, 扫面完成后 
   `/home/test/doc`目录会出现在`admin`用户下文件夹中

   **⚠️注意:**  volumes下挂载的文件夹需要相互独立, 例如: 
  ```yml
volumes:
      - /home/test/doc/files:/jmalcloud/files
      - /home/test/doc:/jmalcloud/files/admin/doc
# /home/test/doc 包含了 /home/test/doc/files
```
**2. 全文搜索: v2.8.0已支持**

**Comment by death4444** [comment]
已经用上了。cool！！
