### ISSUE TITLE
这份文件无法保存。请检查连接设置或联系您的管理员。

### ISSUE THREAD

**Issue by shuzepeng** [jamebal/jmal-cloud-view#88]
本地部署后，打开文件office文件报这份文件无法保存。请检查连接设置或联系您的管理员。callbackUrl用的是本地ip会有问题吗？还是必须要公网ip

**Comment by jamebal** [comment]
不需要公网ip, 刷新整个界面试试

**Comment by jamebal** [comment]
`callbackUrl`这个地址是onlyoffice的会调地址, 只要保证在onlyoffice容器内能访问到后端地址就行
前端 -->  onlyoffice --> 后端

**Comment by shuzepeng** [comment]
> `callbackUrl`这个地址是onlyoffice的回调地址, 只要保证在onlyoffice容器内能访问到后端地址就行, 一般使用本机的局域网ip,而不是localhost 前端 --> onlyoffice --> 后端

好的，我看下回调地址通不通，感觉大佬

**Comment by jamebal** [comment]
to #74
