### ISSUE TITLE
下载文件夹提示所选文件夹为空

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#89]
我在下载文件夹时显示文件夹为空，但是文件夹内是有文件的
![mmexport1715270433173.png](https://github.com/jamebal/jmal-cloud-view/assets/106538519/8eb50b34-1a7c-47b7-af9d-67a009313916)

![mmexport1715270473076.png](https://github.com/jamebal/jmal-cloud-view/assets/106538519/cab539f6-293d-4f0e-9eb6-d5309473eb18)

**Comment by Xiaoph123** [comment]
补充：
我用的是最新版本v2.8.0
当我分享了一个文件夹后，点击复制下载链接，依然是下载不了。

复制下载链接的路径对比：
上一个版本：
https://域名/api/public/s/packageDownload?shareId=65e732117e867b38d69cd4d3&fileIds=65e72adff56c2b887aa80269&share-token=undefined
v2.8.0版本
https://域名/api/file/用户账号/%E7%A0%B4%E8%A7%A3%E8%BD%AF%E4%BB%B6/%E7%8C%AB%E5%BD%B1%E8%A7%86

**Comment by jamebal** [comment]
下个版本修复

**Comment by jamebal** [comment]
v2.8.1已修复该问题

**Comment by Xiaoph123** [comment]
> v2.8.1已修复该问题

好的，感谢大佬
