### ISSUE TITLE
想请问一下，该网盘是徒手从零搭建，还是踩在巨人的肩膀上？

### ISSUE THREAD

**Issue by Nixiak-nan** [jamebal/jmal-cloud-view#9]
感谢作者制作出如此精美的网盘。如题

**Comment by jamebal** [comment]
当然是在巨人的肩膀上创作的:grin:

**Comment by Nixiak-nan** [comment]
请问能给下“巨人”的项目地址吗？

**Comment by jamebal** [comment]
用到项目在这里：https://github.com/jamebal/jmal-cloud-view/blob/master/package.json
主要就是[vue](https://github.com/vuejs/vue)、[elementUI](https://github.com/ElemeFE/element)、[vditor](https://github.com/Vanessa219/vditor)等等, 除了这些基本是从零开始的

**Comment by Nixiak-nan** [comment]
好的，感谢。我本来的意思是以为您基于别人的网盘项目二次开发，看样子就主要使用了开源库，而项目是从零开始，很佩服。最后还是再感谢一次作者提供如此优秀、精美的网盘项目

**Comment by jamebal** [comment]
谢谢，有问题或建议可以提哦👏
