### ISSUE TITLE
文档安全令牌的格式不正确,请与您的文档服务器管理员联系。

### ISSUE THREAD

**Issue by Bmixo** [jamebal/jmal-cloud-view#93]
![image](https://github.com/jamebal/jmal-cloud-view/assets/25509024/2db8c690-5141-4b23-a37f-d4d52a7024e4)
![image](https://github.com/jamebal/jmal-cloud-view/assets/25509024/a3c1a0f8-73eb-48d0-b9da-bdd9584a8f98)

无法使用外部部署带有验证的onlyoffice documentserver

**Comment by jamebal** [comment]
to #94
