### ISSUE TITLE
优化建议：添加从docker env获取配置信息功能

### ISSUE THREAD

**Issue by Bmixo** [jamebal/jmal-cloud-view#94]
https://github.com/jamebal/jmal-cloud-view/blob/1d979b907e1f61d5ff62647565c14015405bf52b/src/utils/file-config.js#L20

**Comment by jamebal** [comment]
你是想自定义onlyoffice的地址 以及 office 的回调地址吗

**Comment by Bmixo** [comment]
> 你是想自定义onlyoffice的地址 以及 office 的回调地址吗

目前是的，但是除了onlyoffice也应该还有其他配置吧，我应该会自己打包一个本地的

**Comment by Bmixo** [comment]
是的，也可以是其他配置信息，我已经重新打包换修改onlyoffice的地址了。
![image](https://github.com/jamebal/jmal-cloud-view/assets/25509024/527af321-ce02-4240-ab60-310c94edfed8)
