### ISSUE TITLE
博客地址跳转错误

### ISSUE THREAD

**Issue by xiaoshun111** [jamebal/jmal-cloud-view#96]
可不可以在后台配置地址，在地址栏输入地址太麻烦了
![image](https://github.com/jamebal/jmal-cloud-view/assets/95558715/530bccce-d0a5-430b-a720-f62a56ba1bb3)

**Comment by jamebal** [comment]
在系统管理-->菜单管理里面可以修改地址

**Comment by xiaoshun111** [comment]
多谢
